[package]
name = "screen-recorder"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
windows.workspace = true
# interprocess.workspace = true
# shared_memory.workspace = true
glad-gl.workspace = true
shmem.workspace = true
vulkanalia = { version = "0.25.0", features = ["libloading", "window"] }
retour = { version = "0.3.1" }
dtor = "0.0.6"
