[package]
name = "injector"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = { version = "0.35" }
winit = { version = "0.30.11", features = ["rwh_06"] }
egui-directx11 = { git = "https://github.com/AlsoSylv/egui-directx11.git" }
egui = "0.32.3"
egui-winit = "0.32.3"
windows.workspace = true
shmem.workspace = true
shared_defs = { version = "0.1.0", path = "../shared_defs" }
