#![allow(non_snake_case)]

pub use self::enumerations::*;
pub use self::functions::*;
pub use self::types::*;

use std::cell::Cell;
use std::os::raw::c_void;

#[derive(Clone)]
struct FnPtr {
    ptr: Cell<*const c_void>,
    is_loaded: Cell<bool>,
}

#[allow(dead_code)]
impl FnPtr {
    fn new(ptr: *const c_void) -> FnPtr {
        if !ptr.is_null() {
            FnPtr {
                ptr: Cell::new(ptr),
                is_loaded: Cell::new(true),
            }
        } else {
            FnPtr {
                ptr: Cell::new(FnPtr::not_initialized as *const c_void),
                is_loaded: Cell::new(false),
            }
        }
    }

    fn set_ptr(&self, ptr: *const c_void) {
        let new = Self::new(ptr);
        self.ptr.set(new.ptr.into_inner());
        self.is_loaded.set(new.is_loaded.into_inner());
    }

    fn aliased(&mut self, other: *const FnPtr) {
        unsafe {
            if !self.is_loaded.get() && (*other).is_loaded.get() {
                *self = (*other).clone();
            }
        }
    }

    #[inline(never)]
    fn not_initialized() -> ! {
        panic!("gl: function not initialized")
    }
}

unsafe impl Sync for FnPtr {}
unsafe impl Send for FnPtr {}

pub mod types {
    #![allow(dead_code, non_snake_case, non_camel_case_types)]

    use std::os::raw;

    pub type GLvoid = raw::c_void;

    pub type GLbyte = raw::c_char;
    pub type GLubyte = raw::c_uchar;
    pub type GLchar = raw::c_char;
    pub type GLboolean = raw::c_uchar;

    pub type GLshort = raw::c_short;
    pub type GLushort = raw::c_ushort;

    pub type GLint = raw::c_int;
    pub type GLuint = raw::c_uint;
    pub type GLint64 = i64;
    pub type GLuint64 = u64;

    pub type GLintptr = isize;
    pub type GLsizeiptr = isize;
    pub type GLintptrARB = isize;
    pub type GLsizeiptrARB = isize;
    pub type GLint64EXT = i64;
    pub type GLuint64EXT = u64;

    pub type GLsizei = GLint;
    pub type GLclampx = raw::c_int;
    pub type GLfixed = GLint;
    pub type GLhalf = raw::c_ushort;
    pub type GLhalfNV = raw::c_ushort;
    pub type GLhalfARB = raw::c_ushort;

    pub type GLenum = raw::c_uint;
    pub type GLbitfield = raw::c_uint;

    pub type GLfloat = raw::c_float;
    pub type GLdouble = raw::c_double;
    pub type GLclampf = raw::c_float;
    pub type GLclampd = raw::c_double;

    pub type GLcharARB = raw::c_char;

    #[cfg(target_os = "macos")]
    pub type GLhandleARB = *const raw::c_void;
    #[cfg(not(target_os = "macos"))]
    pub type GLhandleARB = raw::c_uint;

    pub enum __GLsync {}

    pub type GLsync = *const __GLsync;

    pub enum _cl_context {}

    pub enum _cl_event {}

    pub type GLvdpauSurfaceNV = GLintptr;
    pub type GLeglClientBufferEXT = *const raw::c_void;
    pub type GLeglImageOES = *const raw::c_void;

    pub type GLDEBUGPROC = extern "system" fn(
        source: GLenum,
        type_: GLenum,
        id: GLuint,
        severity: GLenum,
        length: GLsizei,
        message: *const GLchar,
        userParam: *mut raw::c_void,
    );
    pub type GLDEBUGPROCARB = extern "system" fn(
        source: GLenum,
        type_: GLenum,
        id: GLuint,
        severity: GLenum,
        length: GLsizei,
        message: *const GLchar,
        userParam: *mut raw::c_void,
    );
    pub type GLDEBUGPROCKHR = extern "system" fn(
        source: GLenum,
        type_: GLenum,
        id: GLuint,
        severity: GLenum,
        length: GLsizei,
        message: *const GLchar,
        userParam: *mut GLvoid,
    );
    pub type GLDEBUGPROCAMD = extern "system" fn(
        id: GLuint,
        category: GLenum,
        severity: GLenum,
        length: GLsizei,
        message: *const GLchar,
        userParam: *mut GLvoid,
    );
    pub type GLVULKANPROCNV = extern "system" fn();
}

pub mod enumerations {
    #![allow(dead_code, non_upper_case_globals, unused_imports)]

    use super::types::*;
    use std::os::raw::*;

    pub const _2D: c_uint = 0x0600;
    pub const _2_BYTES: c_uint = 0x1407;
    pub const _3D: c_uint = 0x0601;
    pub const _3D_COLOR: c_uint = 0x0602;
    pub const _3D_COLOR_TEXTURE: c_uint = 0x0603;
    pub const _3_BYTES: c_uint = 0x1408;
    pub const _4D_COLOR_TEXTURE: c_uint = 0x0604;
    pub const _4_BYTES: c_uint = 0x1409;
    pub const ACCUM: c_uint = 0x0100;
    pub const ACCUM_ALPHA_BITS: c_uint = 0x0D5B;
    pub const ACCUM_BLUE_BITS: c_uint = 0x0D5A;
    pub const ACCUM_BUFFER_BIT: c_uint = 0x00000200;
    pub const ACCUM_CLEAR_VALUE: c_uint = 0x0B80;
    pub const ACCUM_GREEN_BITS: c_uint = 0x0D59;
    pub const ACCUM_RED_BITS: c_uint = 0x0D58;
    pub const ADD: c_uint = 0x0104;
    pub const ALL_ATTRIB_BITS: c_uint = 0xFFFFFFFF;
    pub const ALPHA: c_uint = 0x1906;
    pub const ALPHA12: c_uint = 0x803D;
    pub const ALPHA16: c_uint = 0x803E;
    pub const ALPHA4: c_uint = 0x803B;
    pub const ALPHA8: c_uint = 0x803C;
    pub const ALPHA_BIAS: c_uint = 0x0D1D;
    pub const ALPHA_BITS: c_uint = 0x0D55;
    pub const ALPHA_SCALE: c_uint = 0x0D1C;
    pub const ALPHA_TEST: c_uint = 0x0BC0;
    pub const ALPHA_TEST_FUNC: c_uint = 0x0BC1;
    pub const ALPHA_TEST_REF: c_uint = 0x0BC2;
    pub const ALWAYS: c_uint = 0x0207;
    pub const AMBIENT: c_uint = 0x1200;
    pub const AMBIENT_AND_DIFFUSE: c_uint = 0x1602;
    pub const AND: c_uint = 0x1501;
    pub const AND_INVERTED: c_uint = 0x1504;
    pub const AND_REVERSE: c_uint = 0x1502;
    pub const ATTRIB_STACK_DEPTH: c_uint = 0x0BB0;
    pub const AUTO_NORMAL: c_uint = 0x0D80;
    pub const AUX0: c_uint = 0x0409;
    pub const AUX1: c_uint = 0x040A;
    pub const AUX2: c_uint = 0x040B;
    pub const AUX3: c_uint = 0x040C;
    pub const AUX_BUFFERS: c_uint = 0x0C00;
    pub const BACK: c_uint = 0x0405;
    pub const BACK_LEFT: c_uint = 0x0402;
    pub const BACK_RIGHT: c_uint = 0x0403;
    pub const BITMAP: c_uint = 0x1A00;
    pub const BITMAP_TOKEN: c_uint = 0x0704;
    pub const BLEND: c_uint = 0x0BE2;
    pub const BLEND_DST: c_uint = 0x0BE0;
    pub const BLEND_SRC: c_uint = 0x0BE1;
    pub const BLUE: c_uint = 0x1905;
    pub const BLUE_BIAS: c_uint = 0x0D1B;
    pub const BLUE_BITS: c_uint = 0x0D54;
    pub const BLUE_SCALE: c_uint = 0x0D1A;
    pub const BYTE: c_uint = 0x1400;
    pub const C3F_V3F: c_uint = 0x2A24;
    pub const C4F_N3F_V3F: c_uint = 0x2A26;
    pub const C4UB_V2F: c_uint = 0x2A22;
    pub const C4UB_V3F: c_uint = 0x2A23;
    pub const CCW: c_uint = 0x0901;
    pub const CLAMP: c_uint = 0x2900;
    pub const CLEAR: c_uint = 0x1500;
    pub const CLIENT_ALL_ATTRIB_BITS: c_uint = 0xFFFFFFFF;
    pub const CLIENT_ATTRIB_STACK_DEPTH: c_uint = 0x0BB1;
    pub const CLIENT_PIXEL_STORE_BIT: c_uint = 0x00000001;
    pub const CLIENT_VERTEX_ARRAY_BIT: c_uint = 0x00000002;
    pub const CLIP_PLANE0: c_uint = 0x3000;
    pub const CLIP_PLANE1: c_uint = 0x3001;
    pub const CLIP_PLANE2: c_uint = 0x3002;
    pub const CLIP_PLANE3: c_uint = 0x3003;
    pub const CLIP_PLANE4: c_uint = 0x3004;
    pub const CLIP_PLANE5: c_uint = 0x3005;
    pub const COEFF: c_uint = 0x0A00;
    pub const COLOR: c_uint = 0x1800;
    pub const COLOR_ARRAY: c_uint = 0x8076;
    pub const COLOR_ARRAY_POINTER: c_uint = 0x8090;
    pub const COLOR_ARRAY_SIZE: c_uint = 0x8081;
    pub const COLOR_ARRAY_STRIDE: c_uint = 0x8083;
    pub const COLOR_ARRAY_TYPE: c_uint = 0x8082;
    pub const COLOR_BUFFER_BIT: c_uint = 0x00004000;
    pub const COLOR_CLEAR_VALUE: c_uint = 0x0C22;
    pub const COLOR_INDEX: c_uint = 0x1900;
    pub const COLOR_INDEXES: c_uint = 0x1603;
    pub const COLOR_LOGIC_OP: c_uint = 0x0BF2;
    pub const COLOR_MATERIAL: c_uint = 0x0B57;
    pub const COLOR_MATERIAL_FACE: c_uint = 0x0B55;
    pub const COLOR_MATERIAL_PARAMETER: c_uint = 0x0B56;
    pub const COLOR_WRITEMASK: c_uint = 0x0C23;
    pub const COMPILE: c_uint = 0x1300;
    pub const COMPILE_AND_EXECUTE: c_uint = 0x1301;
    pub const CONSTANT_ATTENUATION: c_uint = 0x1207;
    pub const COPY: c_uint = 0x1503;
    pub const COPY_INVERTED: c_uint = 0x150C;
    pub const COPY_PIXEL_TOKEN: c_uint = 0x0706;
    pub const CULL_FACE: c_uint = 0x0B44;
    pub const CULL_FACE_MODE: c_uint = 0x0B45;
    pub const CURRENT_BIT: c_uint = 0x00000001;
    pub const CURRENT_COLOR: c_uint = 0x0B00;
    pub const CURRENT_INDEX: c_uint = 0x0B01;
    pub const CURRENT_NORMAL: c_uint = 0x0B02;
    pub const CURRENT_RASTER_COLOR: c_uint = 0x0B04;
    pub const CURRENT_RASTER_DISTANCE: c_uint = 0x0B09;
    pub const CURRENT_RASTER_INDEX: c_uint = 0x0B05;
    pub const CURRENT_RASTER_POSITION: c_uint = 0x0B07;
    pub const CURRENT_RASTER_POSITION_VALID: c_uint = 0x0B08;
    pub const CURRENT_RASTER_TEXTURE_COORDS: c_uint = 0x0B06;
    pub const CURRENT_TEXTURE_COORDS: c_uint = 0x0B03;
    pub const CW: c_uint = 0x0900;
    pub const DECAL: c_uint = 0x2101;
    pub const DECR: c_uint = 0x1E03;
    pub const DEDICATED_MEMORY_OBJECT_EXT: c_uint = 0x9581;
    pub const DEPTH: c_uint = 0x1801;
    pub const DEPTH_BIAS: c_uint = 0x0D1F;
    pub const DEPTH_BITS: c_uint = 0x0D56;
    pub const DEPTH_BUFFER_BIT: c_uint = 0x00000100;
    pub const DEPTH_CLEAR_VALUE: c_uint = 0x0B73;
    pub const DEPTH_COMPONENT: c_uint = 0x1902;
    pub const DEPTH_FUNC: c_uint = 0x0B74;
    pub const DEPTH_RANGE: c_uint = 0x0B70;
    pub const DEPTH_SCALE: c_uint = 0x0D1E;
    pub const DEPTH_TEST: c_uint = 0x0B71;
    pub const DEPTH_WRITEMASK: c_uint = 0x0B72;
    pub const DEVICE_LUID_EXT: c_uint = 0x9599;
    pub const DEVICE_NODE_MASK_EXT: c_uint = 0x959A;
    pub const DEVICE_UUID_EXT: c_uint = 0x9597;
    pub const DIFFUSE: c_uint = 0x1201;
    pub const DITHER: c_uint = 0x0BD0;
    pub const DOMAIN: c_uint = 0x0A02;
    pub const DONT_CARE: c_uint = 0x1100;
    pub const DOUBLE: c_uint = 0x140A;
    pub const DOUBLEBUFFER: c_uint = 0x0C32;
    pub const DRAW_BUFFER: c_uint = 0x0C01;
    pub const DRAW_PIXEL_TOKEN: c_uint = 0x0705;
    pub const DRIVER_UUID_EXT: c_uint = 0x9598;
    pub const DST_ALPHA: c_uint = 0x0304;
    pub const DST_COLOR: c_uint = 0x0306;
    pub const EDGE_FLAG: c_uint = 0x0B43;
    pub const EDGE_FLAG_ARRAY: c_uint = 0x8079;
    pub const EDGE_FLAG_ARRAY_POINTER: c_uint = 0x8093;
    pub const EDGE_FLAG_ARRAY_STRIDE: c_uint = 0x808C;
    pub const EMISSION: c_uint = 0x1600;
    pub const ENABLE_BIT: c_uint = 0x00002000;
    pub const EQUAL: c_uint = 0x0202;
    pub const EQUIV: c_uint = 0x1509;
    pub const EVAL_BIT: c_uint = 0x00010000;
    pub const EXP: c_uint = 0x0800;
    pub const EXP2: c_uint = 0x0801;
    pub const EXTENSIONS: c_uint = 0x1F03;
    pub const EYE_LINEAR: c_uint = 0x2400;
    pub const EYE_PLANE: c_uint = 0x2502;
    pub const FALSE: c_uchar = 0;
    pub const FASTEST: c_uint = 0x1101;
    pub const FEEDBACK: c_uint = 0x1C01;
    pub const FEEDBACK_BUFFER_POINTER: c_uint = 0x0DF0;
    pub const FEEDBACK_BUFFER_SIZE: c_uint = 0x0DF1;
    pub const FEEDBACK_BUFFER_TYPE: c_uint = 0x0DF2;
    pub const FILL: c_uint = 0x1B02;
    pub const FLAT: c_uint = 0x1D00;
    pub const FLOAT: c_uint = 0x1406;
    pub const FOG: c_uint = 0x0B60;
    pub const FOG_BIT: c_uint = 0x00000080;
    pub const FOG_COLOR: c_uint = 0x0B66;
    pub const FOG_DENSITY: c_uint = 0x0B62;
    pub const FOG_END: c_uint = 0x0B64;
    pub const FOG_HINT: c_uint = 0x0C54;
    pub const FOG_INDEX: c_uint = 0x0B61;
    pub const FOG_MODE: c_uint = 0x0B65;
    pub const FOG_START: c_uint = 0x0B63;
    pub const FRONT: c_uint = 0x0404;
    pub const FRONT_AND_BACK: c_uint = 0x0408;
    pub const FRONT_FACE: c_uint = 0x0B46;
    pub const FRONT_LEFT: c_uint = 0x0400;
    pub const FRONT_RIGHT: c_uint = 0x0401;
    pub const GEQUAL: c_uint = 0x0206;
    pub const GREATER: c_uint = 0x0204;
    pub const GREEN: c_uint = 0x1904;
    pub const GREEN_BIAS: c_uint = 0x0D19;
    pub const GREEN_BITS: c_uint = 0x0D53;
    pub const GREEN_SCALE: c_uint = 0x0D18;
    pub const HANDLE_TYPE_D3D11_IMAGE_EXT: c_uint = 0x958B;
    pub const HANDLE_TYPE_D3D11_IMAGE_KMT_EXT: c_uint = 0x958C;
    pub const HANDLE_TYPE_D3D12_RESOURCE_EXT: c_uint = 0x958A;
    pub const HANDLE_TYPE_D3D12_TILEPOOL_EXT: c_uint = 0x9589;
    pub const HANDLE_TYPE_OPAQUE_WIN32_EXT: c_uint = 0x9587;
    pub const HANDLE_TYPE_OPAQUE_WIN32_KMT_EXT: c_uint = 0x9588;
    pub const HINT_BIT: c_uint = 0x00008000;
    pub const INCR: c_uint = 0x1E02;
    pub const INDEX_ARRAY: c_uint = 0x8077;
    pub const INDEX_ARRAY_POINTER: c_uint = 0x8091;
    pub const INDEX_ARRAY_STRIDE: c_uint = 0x8086;
    pub const INDEX_ARRAY_TYPE: c_uint = 0x8085;
    pub const INDEX_BITS: c_uint = 0x0D51;
    pub const INDEX_CLEAR_VALUE: c_uint = 0x0C20;
    pub const INDEX_LOGIC_OP: c_uint = 0x0BF1;
    pub const INDEX_MODE: c_uint = 0x0C30;
    pub const INDEX_OFFSET: c_uint = 0x0D13;
    pub const INDEX_SHIFT: c_uint = 0x0D12;
    pub const INDEX_WRITEMASK: c_uint = 0x0C21;
    pub const INT: c_uint = 0x1404;
    pub const INTENSITY: c_uint = 0x8049;
    pub const INTENSITY12: c_uint = 0x804C;
    pub const INTENSITY16: c_uint = 0x804D;
    pub const INTENSITY4: c_uint = 0x804A;
    pub const INTENSITY8: c_uint = 0x804B;
    pub const INVALID_ENUM: c_uint = 0x0500;
    pub const INVALID_OPERATION: c_uint = 0x0502;
    pub const INVALID_VALUE: c_uint = 0x0501;
    pub const INVERT: c_uint = 0x150A;
    pub const KEEP: c_uint = 0x1E00;
    pub const LEFT: c_uint = 0x0406;
    pub const LEQUAL: c_uint = 0x0203;
    pub const LESS: c_uint = 0x0201;
    pub const LIGHT0: c_uint = 0x4000;
    pub const LIGHT1: c_uint = 0x4001;
    pub const LIGHT2: c_uint = 0x4002;
    pub const LIGHT3: c_uint = 0x4003;
    pub const LIGHT4: c_uint = 0x4004;
    pub const LIGHT5: c_uint = 0x4005;
    pub const LIGHT6: c_uint = 0x4006;
    pub const LIGHT7: c_uint = 0x4007;
    pub const LIGHTING: c_uint = 0x0B50;
    pub const LIGHTING_BIT: c_uint = 0x00000040;
    pub const LIGHT_MODEL_AMBIENT: c_uint = 0x0B53;
    pub const LIGHT_MODEL_LOCAL_VIEWER: c_uint = 0x0B51;
    pub const LIGHT_MODEL_TWO_SIDE: c_uint = 0x0B52;
    pub const LINE: c_uint = 0x1B01;
    pub const LINEAR: c_uint = 0x2601;
    pub const LINEAR_ATTENUATION: c_uint = 0x1208;
    pub const LINEAR_MIPMAP_LINEAR: c_uint = 0x2703;
    pub const LINEAR_MIPMAP_NEAREST: c_uint = 0x2701;
    pub const LINEAR_TILING_EXT: c_uint = 0x9585;
    pub const LINES: c_uint = 0x0001;
    pub const LINE_BIT: c_uint = 0x00000004;
    pub const LINE_LOOP: c_uint = 0x0002;
    pub const LINE_RESET_TOKEN: c_uint = 0x0707;
    pub const LINE_SMOOTH: c_uint = 0x0B20;
    pub const LINE_SMOOTH_HINT: c_uint = 0x0C52;
    pub const LINE_STIPPLE: c_uint = 0x0B24;
    pub const LINE_STIPPLE_PATTERN: c_uint = 0x0B25;
    pub const LINE_STIPPLE_REPEAT: c_uint = 0x0B26;
    pub const LINE_STRIP: c_uint = 0x0003;
    pub const LINE_TOKEN: c_uint = 0x0702;
    pub const LINE_WIDTH: c_uint = 0x0B21;
    pub const LINE_WIDTH_GRANULARITY: c_uint = 0x0B23;
    pub const LINE_WIDTH_RANGE: c_uint = 0x0B22;
    pub const LIST_BASE: c_uint = 0x0B32;
    pub const LIST_BIT: c_uint = 0x00020000;
    pub const LIST_INDEX: c_uint = 0x0B33;
    pub const LIST_MODE: c_uint = 0x0B30;
    pub const LOAD: c_uint = 0x0101;
    pub const LOGIC_OP: c_uint = 0x0BF1;
    pub const LOGIC_OP_MODE: c_uint = 0x0BF0;
    pub const LUID_SIZE_EXT: c_uint = 8;
    pub const LUMINANCE: c_uint = 0x1909;
    pub const LUMINANCE12: c_uint = 0x8041;
    pub const LUMINANCE12_ALPHA12: c_uint = 0x8047;
    pub const LUMINANCE12_ALPHA4: c_uint = 0x8046;
    pub const LUMINANCE16: c_uint = 0x8042;
    pub const LUMINANCE16_ALPHA16: c_uint = 0x8048;
    pub const LUMINANCE4: c_uint = 0x803F;
    pub const LUMINANCE4_ALPHA4: c_uint = 0x8043;
    pub const LUMINANCE6_ALPHA2: c_uint = 0x8044;
    pub const LUMINANCE8: c_uint = 0x8040;
    pub const LUMINANCE8_ALPHA8: c_uint = 0x8045;
    pub const LUMINANCE_ALPHA: c_uint = 0x190A;
    pub const MAP1_COLOR_4: c_uint = 0x0D90;
    pub const MAP1_GRID_DOMAIN: c_uint = 0x0DD0;
    pub const MAP1_GRID_SEGMENTS: c_uint = 0x0DD1;
    pub const MAP1_INDEX: c_uint = 0x0D91;
    pub const MAP1_NORMAL: c_uint = 0x0D92;
    pub const MAP1_TEXTURE_COORD_1: c_uint = 0x0D93;
    pub const MAP1_TEXTURE_COORD_2: c_uint = 0x0D94;
    pub const MAP1_TEXTURE_COORD_3: c_uint = 0x0D95;
    pub const MAP1_TEXTURE_COORD_4: c_uint = 0x0D96;
    pub const MAP1_VERTEX_3: c_uint = 0x0D97;
    pub const MAP1_VERTEX_4: c_uint = 0x0D98;
    pub const MAP2_COLOR_4: c_uint = 0x0DB0;
    pub const MAP2_GRID_DOMAIN: c_uint = 0x0DD2;
    pub const MAP2_GRID_SEGMENTS: c_uint = 0x0DD3;
    pub const MAP2_INDEX: c_uint = 0x0DB1;
    pub const MAP2_NORMAL: c_uint = 0x0DB2;
    pub const MAP2_TEXTURE_COORD_1: c_uint = 0x0DB3;
    pub const MAP2_TEXTURE_COORD_2: c_uint = 0x0DB4;
    pub const MAP2_TEXTURE_COORD_3: c_uint = 0x0DB5;
    pub const MAP2_TEXTURE_COORD_4: c_uint = 0x0DB6;
    pub const MAP2_VERTEX_3: c_uint = 0x0DB7;
    pub const MAP2_VERTEX_4: c_uint = 0x0DB8;
    pub const MAP_COLOR: c_uint = 0x0D10;
    pub const MAP_STENCIL: c_uint = 0x0D11;
    pub const MATRIX_MODE: c_uint = 0x0BA0;
    pub const MAX_ATTRIB_STACK_DEPTH: c_uint = 0x0D35;
    pub const MAX_CLIENT_ATTRIB_STACK_DEPTH: c_uint = 0x0D3B;
    pub const MAX_CLIP_PLANES: c_uint = 0x0D32;
    pub const MAX_EVAL_ORDER: c_uint = 0x0D30;
    pub const MAX_LIGHTS: c_uint = 0x0D31;
    pub const MAX_LIST_NESTING: c_uint = 0x0B31;
    pub const MAX_MODELVIEW_STACK_DEPTH: c_uint = 0x0D36;
    pub const MAX_NAME_STACK_DEPTH: c_uint = 0x0D37;
    pub const MAX_PIXEL_MAP_TABLE: c_uint = 0x0D34;
    pub const MAX_PROJECTION_STACK_DEPTH: c_uint = 0x0D38;
    pub const MAX_TEXTURE_SIZE: c_uint = 0x0D33;
    pub const MAX_TEXTURE_STACK_DEPTH: c_uint = 0x0D39;
    pub const MAX_VIEWPORT_DIMS: c_uint = 0x0D3A;
    pub const MODELVIEW: c_uint = 0x1700;
    pub const MODELVIEW_MATRIX: c_uint = 0x0BA6;
    pub const MODELVIEW_STACK_DEPTH: c_uint = 0x0BA3;
    pub const MODULATE: c_uint = 0x2100;
    pub const MULT: c_uint = 0x0103;
    pub const N3F_V3F: c_uint = 0x2A25;
    pub const NAME_STACK_DEPTH: c_uint = 0x0D70;
    pub const NAND: c_uint = 0x150E;
    pub const NEAREST: c_uint = 0x2600;
    pub const NEAREST_MIPMAP_LINEAR: c_uint = 0x2702;
    pub const NEAREST_MIPMAP_NEAREST: c_uint = 0x2700;
    pub const NEVER: c_uint = 0x0200;
    pub const NICEST: c_uint = 0x1102;
    pub const NONE: c_uint = 0;
    pub const NOOP: c_uint = 0x1505;
    pub const NOR: c_uint = 0x1508;
    pub const NORMALIZE: c_uint = 0x0BA1;
    pub const NORMAL_ARRAY: c_uint = 0x8075;
    pub const NORMAL_ARRAY_POINTER: c_uint = 0x808F;
    pub const NORMAL_ARRAY_STRIDE: c_uint = 0x807F;
    pub const NORMAL_ARRAY_TYPE: c_uint = 0x807E;
    pub const NOTEQUAL: c_uint = 0x0205;
    pub const NO_ERROR: c_uint = 0;
    pub const NUM_DEVICE_UUIDS_EXT: c_uint = 0x9596;
    pub const NUM_TILING_TYPES_EXT: c_uint = 0x9582;
    pub const OBJECT_LINEAR: c_uint = 0x2401;
    pub const OBJECT_PLANE: c_uint = 0x2501;
    pub const ONE: c_uint = 1;
    pub const ONE_MINUS_DST_ALPHA: c_uint = 0x0305;
    pub const ONE_MINUS_DST_COLOR: c_uint = 0x0307;
    pub const ONE_MINUS_SRC_ALPHA: c_uint = 0x0303;
    pub const ONE_MINUS_SRC_COLOR: c_uint = 0x0301;
    pub const OPTIMAL_TILING_EXT: c_uint = 0x9584;
    pub const OR: c_uint = 0x1507;
    pub const ORDER: c_uint = 0x0A01;
    pub const OR_INVERTED: c_uint = 0x150D;
    pub const OR_REVERSE: c_uint = 0x150B;
    pub const OUT_OF_MEMORY: c_uint = 0x0505;
    pub const PACK_ALIGNMENT: c_uint = 0x0D05;
    pub const PACK_LSB_FIRST: c_uint = 0x0D01;
    pub const PACK_ROW_LENGTH: c_uint = 0x0D02;
    pub const PACK_SKIP_PIXELS: c_uint = 0x0D04;
    pub const PACK_SKIP_ROWS: c_uint = 0x0D03;
    pub const PACK_SWAP_BYTES: c_uint = 0x0D00;
    pub const PASS_THROUGH_TOKEN: c_uint = 0x0700;
    pub const PERSPECTIVE_CORRECTION_HINT: c_uint = 0x0C50;
    pub const PIXEL_MAP_A_TO_A: c_uint = 0x0C79;
    pub const PIXEL_MAP_A_TO_A_SIZE: c_uint = 0x0CB9;
    pub const PIXEL_MAP_B_TO_B: c_uint = 0x0C78;
    pub const PIXEL_MAP_B_TO_B_SIZE: c_uint = 0x0CB8;
    pub const PIXEL_MAP_G_TO_G: c_uint = 0x0C77;
    pub const PIXEL_MAP_G_TO_G_SIZE: c_uint = 0x0CB7;
    pub const PIXEL_MAP_I_TO_A: c_uint = 0x0C75;
    pub const PIXEL_MAP_I_TO_A_SIZE: c_uint = 0x0CB5;
    pub const PIXEL_MAP_I_TO_B: c_uint = 0x0C74;
    pub const PIXEL_MAP_I_TO_B_SIZE: c_uint = 0x0CB4;
    pub const PIXEL_MAP_I_TO_G: c_uint = 0x0C73;
    pub const PIXEL_MAP_I_TO_G_SIZE: c_uint = 0x0CB3;
    pub const PIXEL_MAP_I_TO_I: c_uint = 0x0C70;
    pub const PIXEL_MAP_I_TO_I_SIZE: c_uint = 0x0CB0;
    pub const PIXEL_MAP_I_TO_R: c_uint = 0x0C72;
    pub const PIXEL_MAP_I_TO_R_SIZE: c_uint = 0x0CB2;
    pub const PIXEL_MAP_R_TO_R: c_uint = 0x0C76;
    pub const PIXEL_MAP_R_TO_R_SIZE: c_uint = 0x0CB6;
    pub const PIXEL_MAP_S_TO_S: c_uint = 0x0C71;
    pub const PIXEL_MAP_S_TO_S_SIZE: c_uint = 0x0CB1;
    pub const PIXEL_MODE_BIT: c_uint = 0x00000020;
    pub const POINT: c_uint = 0x1B00;
    pub const POINTS: c_uint = 0x0000;
    pub const POINT_BIT: c_uint = 0x00000002;
    pub const POINT_SIZE: c_uint = 0x0B11;
    pub const POINT_SIZE_GRANULARITY: c_uint = 0x0B13;
    pub const POINT_SIZE_RANGE: c_uint = 0x0B12;
    pub const POINT_SMOOTH: c_uint = 0x0B10;
    pub const POINT_SMOOTH_HINT: c_uint = 0x0C51;
    pub const POINT_TOKEN: c_uint = 0x0701;
    pub const POLYGON: c_uint = 0x0009;
    pub const POLYGON_BIT: c_uint = 0x00000008;
    pub const POLYGON_MODE: c_uint = 0x0B40;
    pub const POLYGON_OFFSET_FACTOR: c_uint = 0x8038;
    pub const POLYGON_OFFSET_FILL: c_uint = 0x8037;
    pub const POLYGON_OFFSET_LINE: c_uint = 0x2A02;
    pub const POLYGON_OFFSET_POINT: c_uint = 0x2A01;
    pub const POLYGON_OFFSET_UNITS: c_uint = 0x2A00;
    pub const POLYGON_SMOOTH: c_uint = 0x0B41;
    pub const POLYGON_SMOOTH_HINT: c_uint = 0x0C53;
    pub const POLYGON_STIPPLE: c_uint = 0x0B42;
    pub const POLYGON_STIPPLE_BIT: c_uint = 0x00000010;
    pub const POLYGON_TOKEN: c_uint = 0x0703;
    pub const POSITION: c_uint = 0x1203;
    pub const PROJECTION: c_uint = 0x1701;
    pub const PROJECTION_MATRIX: c_uint = 0x0BA7;
    pub const PROJECTION_STACK_DEPTH: c_uint = 0x0BA4;
    pub const PROTECTED_MEMORY_OBJECT_EXT: c_uint = 0x959B;
    pub const PROXY_TEXTURE_1D: c_uint = 0x8063;
    pub const PROXY_TEXTURE_2D: c_uint = 0x8064;
    pub const Q: c_uint = 0x2003;
    pub const QUADRATIC_ATTENUATION: c_uint = 0x1209;
    pub const QUADS: c_uint = 0x0007;
    pub const QUAD_STRIP: c_uint = 0x0008;
    pub const R: c_uint = 0x2002;
    pub const R3_G3_B2: c_uint = 0x2A10;
    pub const READ_BUFFER: c_uint = 0x0C02;
    pub const RED: c_uint = 0x1903;
    pub const RED_BIAS: c_uint = 0x0D15;
    pub const RED_BITS: c_uint = 0x0D52;
    pub const RED_SCALE: c_uint = 0x0D14;
    pub const RENDER: c_uint = 0x1C00;
    pub const RENDERER: c_uint = 0x1F01;
    pub const RENDER_MODE: c_uint = 0x0C40;
    pub const REPEAT: c_uint = 0x2901;
    pub const REPLACE: c_uint = 0x1E01;
    pub const RETURN: c_uint = 0x0102;
    pub const RGB: c_uint = 0x1907;
    pub const RGB10: c_uint = 0x8052;
    pub const RGB10_A2: c_uint = 0x8059;
    pub const RGB12: c_uint = 0x8053;
    pub const RGB16: c_uint = 0x8054;
    pub const RGB4: c_uint = 0x804F;
    pub const RGB5: c_uint = 0x8050;
    pub const RGB5_A1: c_uint = 0x8057;
    pub const RGB8: c_uint = 0x8051;
    pub const RGBA: c_uint = 0x1908;
    pub const RGBA12: c_uint = 0x805A;
    pub const RGBA16: c_uint = 0x805B;
    pub const RGBA2: c_uint = 0x8055;
    pub const RGBA4: c_uint = 0x8056;
    pub const RGBA8: c_uint = 0x8058;
    pub const RGBA_MODE: c_uint = 0x0C31;
    pub const RIGHT: c_uint = 0x0407;
    pub const S: c_uint = 0x2000;
    pub const SCISSOR_BIT: c_uint = 0x00080000;
    pub const SCISSOR_BOX: c_uint = 0x0C10;
    pub const SCISSOR_TEST: c_uint = 0x0C11;
    pub const SELECT: c_uint = 0x1C02;
    pub const SELECTION_BUFFER_POINTER: c_uint = 0x0DF3;
    pub const SELECTION_BUFFER_SIZE: c_uint = 0x0DF4;
    pub const SET: c_uint = 0x150F;
    pub const SHADE_MODEL: c_uint = 0x0B54;
    pub const SHININESS: c_uint = 0x1601;
    pub const SHORT: c_uint = 0x1402;
    pub const SMOOTH: c_uint = 0x1D01;
    pub const SPECULAR: c_uint = 0x1202;
    pub const SPHERE_MAP: c_uint = 0x2402;
    pub const SPOT_CUTOFF: c_uint = 0x1206;
    pub const SPOT_DIRECTION: c_uint = 0x1204;
    pub const SPOT_EXPONENT: c_uint = 0x1205;
    pub const SRC_ALPHA: c_uint = 0x0302;
    pub const SRC_ALPHA_SATURATE: c_uint = 0x0308;
    pub const SRC_COLOR: c_uint = 0x0300;
    pub const STACK_OVERFLOW: c_uint = 0x0503;
    pub const STACK_UNDERFLOW: c_uint = 0x0504;
    pub const STENCIL: c_uint = 0x1802;
    pub const STENCIL_BITS: c_uint = 0x0D57;
    pub const STENCIL_BUFFER_BIT: c_uint = 0x00000400;
    pub const STENCIL_CLEAR_VALUE: c_uint = 0x0B91;
    pub const STENCIL_FAIL: c_uint = 0x0B94;
    pub const STENCIL_FUNC: c_uint = 0x0B92;
    pub const STENCIL_INDEX: c_uint = 0x1901;
    pub const STENCIL_PASS_DEPTH_FAIL: c_uint = 0x0B95;
    pub const STENCIL_PASS_DEPTH_PASS: c_uint = 0x0B96;
    pub const STENCIL_REF: c_uint = 0x0B97;
    pub const STENCIL_TEST: c_uint = 0x0B90;
    pub const STENCIL_VALUE_MASK: c_uint = 0x0B93;
    pub const STENCIL_WRITEMASK: c_uint = 0x0B98;
    pub const STEREO: c_uint = 0x0C33;
    pub const SUBPIXEL_BITS: c_uint = 0x0D50;
    pub const T: c_uint = 0x2001;
    pub const T2F_C3F_V3F: c_uint = 0x2A2A;
    pub const T2F_C4F_N3F_V3F: c_uint = 0x2A2C;
    pub const T2F_C4UB_V3F: c_uint = 0x2A29;
    pub const T2F_N3F_V3F: c_uint = 0x2A2B;
    pub const T2F_V3F: c_uint = 0x2A27;
    pub const T4F_C4F_N3F_V4F: c_uint = 0x2A2D;
    pub const T4F_V4F: c_uint = 0x2A28;
    pub const TEXTURE: c_uint = 0x1702;
    pub const TEXTURE_1D: c_uint = 0x0DE0;
    pub const TEXTURE_2D: c_uint = 0x0DE1;
    pub const TEXTURE_ALPHA_SIZE: c_uint = 0x805F;
    pub const TEXTURE_BINDING_1D: c_uint = 0x8068;
    pub const TEXTURE_BINDING_2D: c_uint = 0x8069;
    pub const TEXTURE_BIT: c_uint = 0x00040000;
    pub const TEXTURE_BLUE_SIZE: c_uint = 0x805E;
    pub const TEXTURE_BORDER: c_uint = 0x1005;
    pub const TEXTURE_BORDER_COLOR: c_uint = 0x1004;
    pub const TEXTURE_COMPONENTS: c_uint = 0x1003;
    pub const TEXTURE_COORD_ARRAY: c_uint = 0x8078;
    pub const TEXTURE_COORD_ARRAY_POINTER: c_uint = 0x8092;
    pub const TEXTURE_COORD_ARRAY_SIZE: c_uint = 0x8088;
    pub const TEXTURE_COORD_ARRAY_STRIDE: c_uint = 0x808A;
    pub const TEXTURE_COORD_ARRAY_TYPE: c_uint = 0x8089;
    pub const TEXTURE_ENV: c_uint = 0x2300;
    pub const TEXTURE_ENV_COLOR: c_uint = 0x2201;
    pub const TEXTURE_ENV_MODE: c_uint = 0x2200;
    pub const TEXTURE_GEN_MODE: c_uint = 0x2500;
    pub const TEXTURE_GEN_Q: c_uint = 0x0C63;
    pub const TEXTURE_GEN_R: c_uint = 0x0C62;
    pub const TEXTURE_GEN_S: c_uint = 0x0C60;
    pub const TEXTURE_GEN_T: c_uint = 0x0C61;
    pub const TEXTURE_GREEN_SIZE: c_uint = 0x805D;
    pub const TEXTURE_HEIGHT: c_uint = 0x1001;
    pub const TEXTURE_INTENSITY_SIZE: c_uint = 0x8061;
    pub const TEXTURE_INTERNAL_FORMAT: c_uint = 0x1003;
    pub const TEXTURE_LUMINANCE_SIZE: c_uint = 0x8060;
    pub const TEXTURE_MAG_FILTER: c_uint = 0x2800;
    pub const TEXTURE_MATRIX: c_uint = 0x0BA8;
    pub const TEXTURE_MIN_FILTER: c_uint = 0x2801;
    pub const TEXTURE_PRIORITY: c_uint = 0x8066;
    pub const TEXTURE_RED_SIZE: c_uint = 0x805C;
    pub const TEXTURE_RESIDENT: c_uint = 0x8067;
    pub const TEXTURE_STACK_DEPTH: c_uint = 0x0BA5;
    pub const TEXTURE_TILING_EXT: c_uint = 0x9580;
    pub const TEXTURE_WIDTH: c_uint = 0x1000;
    pub const TEXTURE_WRAP_S: c_uint = 0x2802;
    pub const TEXTURE_WRAP_T: c_uint = 0x2803;
    pub const TILING_TYPES_EXT: c_uint = 0x9583;
    pub const TRANSFORM_BIT: c_uint = 0x00001000;
    pub const TRIANGLES: c_uint = 0x0004;
    pub const TRIANGLE_FAN: c_uint = 0x0006;
    pub const TRIANGLE_STRIP: c_uint = 0x0005;
    pub const TRUE: c_uchar = 1;
    pub const UNPACK_ALIGNMENT: c_uint = 0x0CF5;
    pub const UNPACK_LSB_FIRST: c_uint = 0x0CF1;
    pub const UNPACK_ROW_LENGTH: c_uint = 0x0CF2;
    pub const UNPACK_SKIP_PIXELS: c_uint = 0x0CF4;
    pub const UNPACK_SKIP_ROWS: c_uint = 0x0CF3;
    pub const UNPACK_SWAP_BYTES: c_uint = 0x0CF0;
    pub const UNSIGNED_BYTE: c_uint = 0x1401;
    pub const UNSIGNED_INT: c_uint = 0x1405;
    pub const UNSIGNED_SHORT: c_uint = 0x1403;
    pub const UUID_SIZE_EXT: c_uint = 16;
    pub const V2F: c_uint = 0x2A20;
    pub const V3F: c_uint = 0x2A21;
    pub const VENDOR: c_uint = 0x1F00;
    pub const VERSION: c_uint = 0x1F02;
    pub const VERTEX_ARRAY: c_uint = 0x8074;
    pub const VERTEX_ARRAY_POINTER: c_uint = 0x808E;
    pub const VERTEX_ARRAY_SIZE: c_uint = 0x807A;
    pub const VERTEX_ARRAY_STRIDE: c_uint = 0x807C;
    pub const VERTEX_ARRAY_TYPE: c_uint = 0x807B;
    pub const VIEWPORT: c_uint = 0x0BA2;
    pub const VIEWPORT_BIT: c_uint = 0x00000800;
    pub const XOR: c_uint = 0x1506;
    pub const ZERO: c_uint = 0;
    pub const ZOOM_X: c_uint = 0x0D16;
    pub const ZOOM_Y: c_uint = 0x0D17;
}

pub mod functions {
    #![allow(non_snake_case, unused_variables, dead_code, unused_imports)]

    use super::types::*;
    use super::*;
    use std::mem::transmute;
    use std::os::raw::*;

    macro_rules! func {
        ($fun:ident, $ret:ty, $($name:ident: $typ:ty),*) => {
            #[inline] pub unsafe fn $fun($($name: $typ),*) -> $ret {
                transmute::<_, extern "system" fn($($typ),*) -> $ret>(storage::$fun.ptr.clone())($($name),*)
            }
        }
    }

    func!(Accum, (), op: GLenum, value: GLfloat);
    func!(AlphaFunc, (), func: GLenum, ref_: GLfloat);
    func!(AreTexturesResident, GLboolean, n: GLsizei, textures: *const GLuint, residences: *mut GLboolean);
    func!(ArrayElement, (), i: GLint);
    func!(Begin, (), mode: GLenum);
    func!(BindTexture, (), target: GLenum, texture: GLuint);
    func!(Bitmap, (), width: GLsizei, height: GLsizei, xorig: GLfloat, yorig: GLfloat, xmove: GLfloat, ymove: GLfloat, bitmap: *const GLubyte);
    func!(BlendFunc, (), sfactor: GLenum, dfactor: GLenum);
    func!(BufferStorageMemEXT, (), target: GLenum, size: GLsizeiptr, memory: GLuint, offset: GLuint64);
    func!(CallList, (), list: GLuint);
    func!(CallLists, (), n: GLsizei, type_: GLenum, lists: *const c_void);
    func!(Clear, (), mask: GLbitfield);
    func!(ClearAccum, (), red: GLfloat, green: GLfloat, blue: GLfloat, alpha: GLfloat);
    func!(ClearColor, (), red: GLfloat, green: GLfloat, blue: GLfloat, alpha: GLfloat);
    func!(ClearDepth, (), depth: GLdouble);
    func!(ClearIndex, (), c: GLfloat);
    func!(ClearStencil, (), s: GLint);
    func!(ClipPlane, (), plane: GLenum, equation: *const GLdouble);
    func!(Color3b, (), red: GLbyte, green: GLbyte, blue: GLbyte);
    func!(Color3bv, (), v: *const GLbyte);
    func!(Color3d, (), red: GLdouble, green: GLdouble, blue: GLdouble);
    func!(Color3dv, (), v: *const GLdouble);
    func!(Color3f, (), red: GLfloat, green: GLfloat, blue: GLfloat);
    func!(Color3fv, (), v: *const GLfloat);
    func!(Color3i, (), red: GLint, green: GLint, blue: GLint);
    func!(Color3iv, (), v: *const GLint);
    func!(Color3s, (), red: GLshort, green: GLshort, blue: GLshort);
    func!(Color3sv, (), v: *const GLshort);
    func!(Color3ub, (), red: GLubyte, green: GLubyte, blue: GLubyte);
    func!(Color3ubv, (), v: *const GLubyte);
    func!(Color3ui, (), red: GLuint, green: GLuint, blue: GLuint);
    func!(Color3uiv, (), v: *const GLuint);
    func!(Color3us, (), red: GLushort, green: GLushort, blue: GLushort);
    func!(Color3usv, (), v: *const GLushort);
    func!(Color4b, (), red: GLbyte, green: GLbyte, blue: GLbyte, alpha: GLbyte);
    func!(Color4bv, (), v: *const GLbyte);
    func!(Color4d, (), red: GLdouble, green: GLdouble, blue: GLdouble, alpha: GLdouble);
    func!(Color4dv, (), v: *const GLdouble);
    func!(Color4f, (), red: GLfloat, green: GLfloat, blue: GLfloat, alpha: GLfloat);
    func!(Color4fv, (), v: *const GLfloat);
    func!(Color4i, (), red: GLint, green: GLint, blue: GLint, alpha: GLint);
    func!(Color4iv, (), v: *const GLint);
    func!(Color4s, (), red: GLshort, green: GLshort, blue: GLshort, alpha: GLshort);
    func!(Color4sv, (), v: *const GLshort);
    func!(Color4ub, (), red: GLubyte, green: GLubyte, blue: GLubyte, alpha: GLubyte);
    func!(Color4ubv, (), v: *const GLubyte);
    func!(Color4ui, (), red: GLuint, green: GLuint, blue: GLuint, alpha: GLuint);
    func!(Color4uiv, (), v: *const GLuint);
    func!(Color4us, (), red: GLushort, green: GLushort, blue: GLushort, alpha: GLushort);
    func!(Color4usv, (), v: *const GLushort);
    func!(ColorMask, (), red: GLboolean, green: GLboolean, blue: GLboolean, alpha: GLboolean);
    func!(ColorMaterial, (), face: GLenum, mode: GLenum);
    func!(ColorPointer, (), size: GLint, type_: GLenum, stride: GLsizei, pointer: *const c_void);
    func!(CopyPixels, (), x: GLint, y: GLint, width: GLsizei, height: GLsizei, type_: GLenum);
    func!(CopyTexImage1D, (), target: GLenum, level: GLint, internalformat: GLenum, x: GLint, y: GLint, width: GLsizei, border: GLint);
    func!(CopyTexImage2D, (), target: GLenum, level: GLint, internalformat: GLenum, x: GLint, y: GLint, width: GLsizei, height: GLsizei, border: GLint);
    func!(CopyTexSubImage1D, (), target: GLenum, level: GLint, xoffset: GLint, x: GLint, y: GLint, width: GLsizei);
    func!(CopyTexSubImage2D, (), target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, x: GLint, y: GLint, width: GLsizei, height: GLsizei);
    func!(CreateMemoryObjectsEXT, (), n: GLsizei, memoryObjects: *mut GLuint);
    func!(CullFace, (), mode: GLenum);
    func!(DeleteLists, (), list: GLuint, range: GLsizei);
    func!(DeleteMemoryObjectsEXT, (), n: GLsizei, memoryObjects: *const GLuint);
    func!(DeleteTextures, (), n: GLsizei, textures: *const GLuint);
    func!(DepthFunc, (), func: GLenum);
    func!(DepthMask, (), flag: GLboolean);
    func!(DepthRange, (), n: GLdouble, f: GLdouble);
    func!(Disable, (), cap: GLenum);
    func!(DisableClientState, (), array: GLenum);
    func!(DrawArrays, (), mode: GLenum, first: GLint, count: GLsizei);
    func!(DrawBuffer, (), buf: GLenum);
    func!(DrawElements, (), mode: GLenum, count: GLsizei, type_: GLenum, indices: *const c_void);
    func!(DrawPixels, (), width: GLsizei, height: GLsizei, format: GLenum, type_: GLenum, pixels: *const c_void);
    func!(EdgeFlag, (), flag: GLboolean);
    func!(EdgeFlagPointer, (), stride: GLsizei, pointer: *const c_void);
    func!(EdgeFlagv, (), flag: *const GLboolean);
    func!(Enable, (), cap: GLenum);
    func!(EnableClientState, (), array: GLenum);
    func!(End, (),);
    func!(EndList, (),);
    func!(EvalCoord1d, (), u: GLdouble);
    func!(EvalCoord1dv, (), u: *const GLdouble);
    func!(EvalCoord1f, (), u: GLfloat);
    func!(EvalCoord1fv, (), u: *const GLfloat);
    func!(EvalCoord2d, (), u: GLdouble, v: GLdouble);
    func!(EvalCoord2dv, (), u: *const GLdouble);
    func!(EvalCoord2f, (), u: GLfloat, v: GLfloat);
    func!(EvalCoord2fv, (), u: *const GLfloat);
    func!(EvalMesh1, (), mode: GLenum, i1: GLint, i2: GLint);
    func!(EvalMesh2, (), mode: GLenum, i1: GLint, i2: GLint, j1: GLint, j2: GLint);
    func!(EvalPoint1, (), i: GLint);
    func!(EvalPoint2, (), i: GLint, j: GLint);
    func!(FeedbackBuffer, (), size: GLsizei, type_: GLenum, buffer: *mut GLfloat);
    func!(Finish, (),);
    func!(Flush, (),);
    func!(Fogf, (), pname: GLenum, param: GLfloat);
    func!(Fogfv, (), pname: GLenum, params: *const GLfloat);
    func!(Fogi, (), pname: GLenum, param: GLint);
    func!(Fogiv, (), pname: GLenum, params: *const GLint);
    func!(FrontFace, (), mode: GLenum);
    func!(Frustum, (), left: GLdouble, right: GLdouble, bottom: GLdouble, top: GLdouble, zNear: GLdouble, zFar: GLdouble);
    func!(GenLists, GLuint, range: GLsizei);
    func!(GenTextures, (), n: GLsizei, textures: *mut GLuint);
    func!(GetBooleanv, (), pname: GLenum, data: *mut GLboolean);
    func!(GetClipPlane, (), plane: GLenum, equation: *mut GLdouble);
    func!(GetDoublev, (), pname: GLenum, data: *mut GLdouble);
    func!(GetError, GLenum,);
    func!(GetFloatv, (), pname: GLenum, data: *mut GLfloat);
    func!(GetIntegerv, (), pname: GLenum, data: *mut GLint);
    func!(GetLightfv, (), light: GLenum, pname: GLenum, params: *mut GLfloat);
    func!(GetLightiv, (), light: GLenum, pname: GLenum, params: *mut GLint);
    func!(GetMapdv, (), target: GLenum, query: GLenum, v: *mut GLdouble);
    func!(GetMapfv, (), target: GLenum, query: GLenum, v: *mut GLfloat);
    func!(GetMapiv, (), target: GLenum, query: GLenum, v: *mut GLint);
    func!(GetMaterialfv, (), face: GLenum, pname: GLenum, params: *mut GLfloat);
    func!(GetMaterialiv, (), face: GLenum, pname: GLenum, params: *mut GLint);
    func!(GetMemoryObjectParameterivEXT, (), memoryObject: GLuint, pname: GLenum, params: *mut GLint);
    func!(GetPixelMapfv, (), map: GLenum, values: *mut GLfloat);
    func!(GetPixelMapuiv, (), map: GLenum, values: *mut GLuint);
    func!(GetPixelMapusv, (), map: GLenum, values: *mut GLushort);
    func!(GetPointerv, (), pname: GLenum, params: *mut *mut c_void);
    func!(GetPolygonStipple, (), mask: *mut GLubyte);
    func!(GetString, *const GLubyte, name: GLenum);
    func!(GetTexEnvfv, (), target: GLenum, pname: GLenum, params: *mut GLfloat);
    func!(GetTexEnviv, (), target: GLenum, pname: GLenum, params: *mut GLint);
    func!(GetTexGendv, (), coord: GLenum, pname: GLenum, params: *mut GLdouble);
    func!(GetTexGenfv, (), coord: GLenum, pname: GLenum, params: *mut GLfloat);
    func!(GetTexGeniv, (), coord: GLenum, pname: GLenum, params: *mut GLint);
    func!(GetTexImage, (), target: GLenum, level: GLint, format: GLenum, type_: GLenum, pixels: *mut c_void);
    func!(GetTexLevelParameterfv, (), target: GLenum, level: GLint, pname: GLenum, params: *mut GLfloat);
    func!(GetTexLevelParameteriv, (), target: GLenum, level: GLint, pname: GLenum, params: *mut GLint);
    func!(GetTexParameterfv, (), target: GLenum, pname: GLenum, params: *mut GLfloat);
    func!(GetTexParameteriv, (), target: GLenum, pname: GLenum, params: *mut GLint);
    func!(GetUnsignedBytei_vEXT, (), target: GLenum, index: GLuint, data: *mut GLubyte);
    func!(GetUnsignedBytevEXT, (), pname: GLenum, data: *mut GLubyte);
    func!(Hint, (), target: GLenum, mode: GLenum);
    func!(ImportMemoryWin32HandleEXT, (), memory: GLuint, size: GLuint64, handleType: GLenum, handle: *mut c_void);
    func!(ImportMemoryWin32NameEXT, (), memory: GLuint, size: GLuint64, handleType: GLenum, name: *const c_void);
    func!(IndexMask, (), mask: GLuint);
    func!(IndexPointer, (), type_: GLenum, stride: GLsizei, pointer: *const c_void);
    func!(Indexd, (), c: GLdouble);
    func!(Indexdv, (), c: *const GLdouble);
    func!(Indexf, (), c: GLfloat);
    func!(Indexfv, (), c: *const GLfloat);
    func!(Indexi, (), c: GLint);
    func!(Indexiv, (), c: *const GLint);
    func!(Indexs, (), c: GLshort);
    func!(Indexsv, (), c: *const GLshort);
    func!(Indexub, (), c: GLubyte);
    func!(Indexubv, (), c: *const GLubyte);
    func!(InitNames, (),);
    func!(InterleavedArrays, (), format: GLenum, stride: GLsizei, pointer: *const c_void);
    func!(IsEnabled, GLboolean, cap: GLenum);
    func!(IsList, GLboolean, list: GLuint);
    func!(IsMemoryObjectEXT, GLboolean, memoryObject: GLuint);
    func!(IsTexture, GLboolean, texture: GLuint);
    func!(LightModelf, (), pname: GLenum, param: GLfloat);
    func!(LightModelfv, (), pname: GLenum, params: *const GLfloat);
    func!(LightModeli, (), pname: GLenum, param: GLint);
    func!(LightModeliv, (), pname: GLenum, params: *const GLint);
    func!(Lightf, (), light: GLenum, pname: GLenum, param: GLfloat);
    func!(Lightfv, (), light: GLenum, pname: GLenum, params: *const GLfloat);
    func!(Lighti, (), light: GLenum, pname: GLenum, param: GLint);
    func!(Lightiv, (), light: GLenum, pname: GLenum, params: *const GLint);
    func!(LineStipple, (), factor: GLint, pattern: GLushort);
    func!(LineWidth, (), width: GLfloat);
    func!(ListBase, (), base: GLuint);
    func!(LoadIdentity, (),);
    func!(LoadMatrixd, (), m: *const GLdouble);
    func!(LoadMatrixf, (), m: *const GLfloat);
    func!(LoadName, (), name: GLuint);
    func!(LogicOp, (), opcode: GLenum);
    func!(Map1d, (), target: GLenum, u1: GLdouble, u2: GLdouble, stride: GLint, order: GLint, points: *const GLdouble);
    func!(Map1f, (), target: GLenum, u1: GLfloat, u2: GLfloat, stride: GLint, order: GLint, points: *const GLfloat);
    func!(Map2d, (), target: GLenum, u1: GLdouble, u2: GLdouble, ustride: GLint, uorder: GLint, v1: GLdouble, v2: GLdouble, vstride: GLint, vorder: GLint, points: *const GLdouble);
    func!(Map2f, (), target: GLenum, u1: GLfloat, u2: GLfloat, ustride: GLint, uorder: GLint, v1: GLfloat, v2: GLfloat, vstride: GLint, vorder: GLint, points: *const GLfloat);
    func!(MapGrid1d, (), un: GLint, u1: GLdouble, u2: GLdouble);
    func!(MapGrid1f, (), un: GLint, u1: GLfloat, u2: GLfloat);
    func!(MapGrid2d, (), un: GLint, u1: GLdouble, u2: GLdouble, vn: GLint, v1: GLdouble, v2: GLdouble);
    func!(MapGrid2f, (), un: GLint, u1: GLfloat, u2: GLfloat, vn: GLint, v1: GLfloat, v2: GLfloat);
    func!(Materialf, (), face: GLenum, pname: GLenum, param: GLfloat);
    func!(Materialfv, (), face: GLenum, pname: GLenum, params: *const GLfloat);
    func!(Materiali, (), face: GLenum, pname: GLenum, param: GLint);
    func!(Materialiv, (), face: GLenum, pname: GLenum, params: *const GLint);
    func!(MatrixMode, (), mode: GLenum);
    func!(MemoryObjectParameterivEXT, (), memoryObject: GLuint, pname: GLenum, params: *const GLint);
    func!(MultMatrixd, (), m: *const GLdouble);
    func!(MultMatrixf, (), m: *const GLfloat);
    func!(NamedBufferStorageMemEXT, (), buffer: GLuint, size: GLsizeiptr, memory: GLuint, offset: GLuint64);
    func!(NewList, (), list: GLuint, mode: GLenum);
    func!(Normal3b, (), nx: GLbyte, ny: GLbyte, nz: GLbyte);
    func!(Normal3bv, (), v: *const GLbyte);
    func!(Normal3d, (), nx: GLdouble, ny: GLdouble, nz: GLdouble);
    func!(Normal3dv, (), v: *const GLdouble);
    func!(Normal3f, (), nx: GLfloat, ny: GLfloat, nz: GLfloat);
    func!(Normal3fv, (), v: *const GLfloat);
    func!(Normal3i, (), nx: GLint, ny: GLint, nz: GLint);
    func!(Normal3iv, (), v: *const GLint);
    func!(Normal3s, (), nx: GLshort, ny: GLshort, nz: GLshort);
    func!(Normal3sv, (), v: *const GLshort);
    func!(NormalPointer, (), type_: GLenum, stride: GLsizei, pointer: *const c_void);
    func!(Ortho, (), left: GLdouble, right: GLdouble, bottom: GLdouble, top: GLdouble, zNear: GLdouble, zFar: GLdouble);
    func!(PassThrough, (), token: GLfloat);
    func!(PixelMapfv, (), map: GLenum, mapsize: GLsizei, values: *const GLfloat);
    func!(PixelMapuiv, (), map: GLenum, mapsize: GLsizei, values: *const GLuint);
    func!(PixelMapusv, (), map: GLenum, mapsize: GLsizei, values: *const GLushort);
    func!(PixelStoref, (), pname: GLenum, param: GLfloat);
    func!(PixelStorei, (), pname: GLenum, param: GLint);
    func!(PixelTransferf, (), pname: GLenum, param: GLfloat);
    func!(PixelTransferi, (), pname: GLenum, param: GLint);
    func!(PixelZoom, (), xfactor: GLfloat, yfactor: GLfloat);
    func!(PointSize, (), size: GLfloat);
    func!(PolygonMode, (), face: GLenum, mode: GLenum);
    func!(PolygonOffset, (), factor: GLfloat, units: GLfloat);
    func!(PolygonStipple, (), mask: *const GLubyte);
    func!(PopAttrib, (),);
    func!(PopClientAttrib, (),);
    func!(PopMatrix, (),);
    func!(PopName, (),);
    func!(PrioritizeTextures, (), n: GLsizei, textures: *const GLuint, priorities: *const GLfloat);
    func!(PushAttrib, (), mask: GLbitfield);
    func!(PushClientAttrib, (), mask: GLbitfield);
    func!(PushMatrix, (),);
    func!(PushName, (), name: GLuint);
    func!(RasterPos2d, (), x: GLdouble, y: GLdouble);
    func!(RasterPos2dv, (), v: *const GLdouble);
    func!(RasterPos2f, (), x: GLfloat, y: GLfloat);
    func!(RasterPos2fv, (), v: *const GLfloat);
    func!(RasterPos2i, (), x: GLint, y: GLint);
    func!(RasterPos2iv, (), v: *const GLint);
    func!(RasterPos2s, (), x: GLshort, y: GLshort);
    func!(RasterPos2sv, (), v: *const GLshort);
    func!(RasterPos3d, (), x: GLdouble, y: GLdouble, z: GLdouble);
    func!(RasterPos3dv, (), v: *const GLdouble);
    func!(RasterPos3f, (), x: GLfloat, y: GLfloat, z: GLfloat);
    func!(RasterPos3fv, (), v: *const GLfloat);
    func!(RasterPos3i, (), x: GLint, y: GLint, z: GLint);
    func!(RasterPos3iv, (), v: *const GLint);
    func!(RasterPos3s, (), x: GLshort, y: GLshort, z: GLshort);
    func!(RasterPos3sv, (), v: *const GLshort);
    func!(RasterPos4d, (), x: GLdouble, y: GLdouble, z: GLdouble, w: GLdouble);
    func!(RasterPos4dv, (), v: *const GLdouble);
    func!(RasterPos4f, (), x: GLfloat, y: GLfloat, z: GLfloat, w: GLfloat);
    func!(RasterPos4fv, (), v: *const GLfloat);
    func!(RasterPos4i, (), x: GLint, y: GLint, z: GLint, w: GLint);
    func!(RasterPos4iv, (), v: *const GLint);
    func!(RasterPos4s, (), x: GLshort, y: GLshort, z: GLshort, w: GLshort);
    func!(RasterPos4sv, (), v: *const GLshort);
    func!(ReadBuffer, (), src: GLenum);
    func!(ReadPixels, (), x: GLint, y: GLint, width: GLsizei, height: GLsizei, format: GLenum, type_: GLenum, pixels: *mut c_void);
    func!(Rectd, (), x1: GLdouble, y1: GLdouble, x2: GLdouble, y2: GLdouble);
    func!(Rectdv, (), v1: *const GLdouble, v2: *const GLdouble);
    func!(Rectf, (), x1: GLfloat, y1: GLfloat, x2: GLfloat, y2: GLfloat);
    func!(Rectfv, (), v1: *const GLfloat, v2: *const GLfloat);
    func!(Recti, (), x1: GLint, y1: GLint, x2: GLint, y2: GLint);
    func!(Rectiv, (), v1: *const GLint, v2: *const GLint);
    func!(Rects, (), x1: GLshort, y1: GLshort, x2: GLshort, y2: GLshort);
    func!(Rectsv, (), v1: *const GLshort, v2: *const GLshort);
    func!(RenderMode, GLint, mode: GLenum);
    func!(Rotated, (), angle: GLdouble, x: GLdouble, y: GLdouble, z: GLdouble);
    func!(Rotatef, (), angle: GLfloat, x: GLfloat, y: GLfloat, z: GLfloat);
    func!(Scaled, (), x: GLdouble, y: GLdouble, z: GLdouble);
    func!(Scalef, (), x: GLfloat, y: GLfloat, z: GLfloat);
    func!(Scissor, (), x: GLint, y: GLint, width: GLsizei, height: GLsizei);
    func!(SelectBuffer, (), size: GLsizei, buffer: *mut GLuint);
    func!(ShadeModel, (), mode: GLenum);
    func!(StencilFunc, (), func: GLenum, ref_: GLint, mask: GLuint);
    func!(StencilMask, (), mask: GLuint);
    func!(StencilOp, (), fail: GLenum, zfail: GLenum, zpass: GLenum);
    func!(TexCoord1d, (), s: GLdouble);
    func!(TexCoord1dv, (), v: *const GLdouble);
    func!(TexCoord1f, (), s: GLfloat);
    func!(TexCoord1fv, (), v: *const GLfloat);
    func!(TexCoord1i, (), s: GLint);
    func!(TexCoord1iv, (), v: *const GLint);
    func!(TexCoord1s, (), s: GLshort);
    func!(TexCoord1sv, (), v: *const GLshort);
    func!(TexCoord2d, (), s: GLdouble, t: GLdouble);
    func!(TexCoord2dv, (), v: *const GLdouble);
    func!(TexCoord2f, (), s: GLfloat, t: GLfloat);
    func!(TexCoord2fv, (), v: *const GLfloat);
    func!(TexCoord2i, (), s: GLint, t: GLint);
    func!(TexCoord2iv, (), v: *const GLint);
    func!(TexCoord2s, (), s: GLshort, t: GLshort);
    func!(TexCoord2sv, (), v: *const GLshort);
    func!(TexCoord3d, (), s: GLdouble, t: GLdouble, r: GLdouble);
    func!(TexCoord3dv, (), v: *const GLdouble);
    func!(TexCoord3f, (), s: GLfloat, t: GLfloat, r: GLfloat);
    func!(TexCoord3fv, (), v: *const GLfloat);
    func!(TexCoord3i, (), s: GLint, t: GLint, r: GLint);
    func!(TexCoord3iv, (), v: *const GLint);
    func!(TexCoord3s, (), s: GLshort, t: GLshort, r: GLshort);
    func!(TexCoord3sv, (), v: *const GLshort);
    func!(TexCoord4d, (), s: GLdouble, t: GLdouble, r: GLdouble, q: GLdouble);
    func!(TexCoord4dv, (), v: *const GLdouble);
    func!(TexCoord4f, (), s: GLfloat, t: GLfloat, r: GLfloat, q: GLfloat);
    func!(TexCoord4fv, (), v: *const GLfloat);
    func!(TexCoord4i, (), s: GLint, t: GLint, r: GLint, q: GLint);
    func!(TexCoord4iv, (), v: *const GLint);
    func!(TexCoord4s, (), s: GLshort, t: GLshort, r: GLshort, q: GLshort);
    func!(TexCoord4sv, (), v: *const GLshort);
    func!(TexCoordPointer, (), size: GLint, type_: GLenum, stride: GLsizei, pointer: *const c_void);
    func!(TexEnvf, (), target: GLenum, pname: GLenum, param: GLfloat);
    func!(TexEnvfv, (), target: GLenum, pname: GLenum, params: *const GLfloat);
    func!(TexEnvi, (), target: GLenum, pname: GLenum, param: GLint);
    func!(TexEnviv, (), target: GLenum, pname: GLenum, params: *const GLint);
    func!(TexGend, (), coord: GLenum, pname: GLenum, param: GLdouble);
    func!(TexGendv, (), coord: GLenum, pname: GLenum, params: *const GLdouble);
    func!(TexGenf, (), coord: GLenum, pname: GLenum, param: GLfloat);
    func!(TexGenfv, (), coord: GLenum, pname: GLenum, params: *const GLfloat);
    func!(TexGeni, (), coord: GLenum, pname: GLenum, param: GLint);
    func!(TexGeniv, (), coord: GLenum, pname: GLenum, params: *const GLint);
    func!(TexImage1D, (), target: GLenum, level: GLint, internalformat: GLint, width: GLsizei, border: GLint, format: GLenum, type_: GLenum, pixels: *const c_void);
    func!(TexImage2D, (), target: GLenum, level: GLint, internalformat: GLint, width: GLsizei, height: GLsizei, border: GLint, format: GLenum, type_: GLenum, pixels: *const c_void);
    func!(TexParameterf, (), target: GLenum, pname: GLenum, param: GLfloat);
    func!(TexParameterfv, (), target: GLenum, pname: GLenum, params: *const GLfloat);
    func!(TexParameteri, (), target: GLenum, pname: GLenum, param: GLint);
    func!(TexParameteriv, (), target: GLenum, pname: GLenum, params: *const GLint);
    func!(TexStorageMem1DEXT, (), target: GLenum, levels: GLsizei, internalFormat: GLenum, width: GLsizei, memory: GLuint, offset: GLuint64);
    func!(TexStorageMem2DEXT, (), target: GLenum, levels: GLsizei, internalFormat: GLenum, width: GLsizei, height: GLsizei, memory: GLuint, offset: GLuint64);
    func!(TexStorageMem2DMultisampleEXT, (), target: GLenum, samples: GLsizei, internalFormat: GLenum, width: GLsizei, height: GLsizei, fixedSampleLocations: GLboolean, memory: GLuint, offset: GLuint64);
    func!(TexStorageMem3DEXT, (), target: GLenum, levels: GLsizei, internalFormat: GLenum, width: GLsizei, height: GLsizei, depth: GLsizei, memory: GLuint, offset: GLuint64);
    func!(TexStorageMem3DMultisampleEXT, (), target: GLenum, samples: GLsizei, internalFormat: GLenum, width: GLsizei, height: GLsizei, depth: GLsizei, fixedSampleLocations: GLboolean, memory: GLuint, offset: GLuint64);
    func!(TexSubImage1D, (), target: GLenum, level: GLint, xoffset: GLint, width: GLsizei, format: GLenum, type_: GLenum, pixels: *const c_void);
    func!(TexSubImage2D, (), target: GLenum, level: GLint, xoffset: GLint, yoffset: GLint, width: GLsizei, height: GLsizei, format: GLenum, type_: GLenum, pixels: *const c_void);
    func!(TextureStorageMem1DEXT, (), texture: GLuint, levels: GLsizei, internalFormat: GLenum, width: GLsizei, memory: GLuint, offset: GLuint64);
    func!(TextureStorageMem2DEXT, (), texture: GLuint, levels: GLsizei, internalFormat: GLenum, width: GLsizei, height: GLsizei, memory: GLuint, offset: GLuint64);
    func!(TextureStorageMem2DMultisampleEXT, (), texture: GLuint, samples: GLsizei, internalFormat: GLenum, width: GLsizei, height: GLsizei, fixedSampleLocations: GLboolean, memory: GLuint, offset: GLuint64);
    func!(TextureStorageMem3DEXT, (), texture: GLuint, levels: GLsizei, internalFormat: GLenum, width: GLsizei, height: GLsizei, depth: GLsizei, memory: GLuint, offset: GLuint64);
    func!(TextureStorageMem3DMultisampleEXT, (), texture: GLuint, samples: GLsizei, internalFormat: GLenum, width: GLsizei, height: GLsizei, depth: GLsizei, fixedSampleLocations: GLboolean, memory: GLuint, offset: GLuint64);
    func!(Translated, (), x: GLdouble, y: GLdouble, z: GLdouble);
    func!(Translatef, (), x: GLfloat, y: GLfloat, z: GLfloat);
    func!(Vertex2d, (), x: GLdouble, y: GLdouble);
    func!(Vertex2dv, (), v: *const GLdouble);
    func!(Vertex2f, (), x: GLfloat, y: GLfloat);
    func!(Vertex2fv, (), v: *const GLfloat);
    func!(Vertex2i, (), x: GLint, y: GLint);
    func!(Vertex2iv, (), v: *const GLint);
    func!(Vertex2s, (), x: GLshort, y: GLshort);
    func!(Vertex2sv, (), v: *const GLshort);
    func!(Vertex3d, (), x: GLdouble, y: GLdouble, z: GLdouble);
    func!(Vertex3dv, (), v: *const GLdouble);
    func!(Vertex3f, (), x: GLfloat, y: GLfloat, z: GLfloat);
    func!(Vertex3fv, (), v: *const GLfloat);
    func!(Vertex3i, (), x: GLint, y: GLint, z: GLint);
    func!(Vertex3iv, (), v: *const GLint);
    func!(Vertex3s, (), x: GLshort, y: GLshort, z: GLshort);
    func!(Vertex3sv, (), v: *const GLshort);
    func!(Vertex4d, (), x: GLdouble, y: GLdouble, z: GLdouble, w: GLdouble);
    func!(Vertex4dv, (), v: *const GLdouble);
    func!(Vertex4f, (), x: GLfloat, y: GLfloat, z: GLfloat, w: GLfloat);
    func!(Vertex4fv, (), v: *const GLfloat);
    func!(Vertex4i, (), x: GLint, y: GLint, z: GLint, w: GLint);
    func!(Vertex4iv, (), v: *const GLint);
    func!(Vertex4s, (), x: GLshort, y: GLshort, z: GLshort, w: GLshort);
    func!(Vertex4sv, (), v: *const GLshort);
    func!(VertexPointer, (), size: GLint, type_: GLenum, stride: GLsizei, pointer: *const c_void);
    func!(Viewport, (), x: GLint, y: GLint, width: GLsizei, height: GLsizei);
}

mod storage {
    #![allow(non_snake_case, non_upper_case_globals)]

    use super::FnPtr;
    use std::cell::Cell;
    use std::os::raw::*;

    macro_rules! store {
        ($name:ident) => {
            pub(super) static $name: FnPtr = FnPtr {
                ptr: Cell::new(FnPtr::not_initialized as *const c_void),
                is_loaded: Cell::new(false),
            };
        };
    }

    store!(Accum);
    store!(AlphaFunc);
    store!(AreTexturesResident);
    store!(ArrayElement);
    store!(Begin);
    store!(BindTexture);
    store!(Bitmap);
    store!(BlendFunc);
    store!(BufferStorageMemEXT);
    store!(CallList);
    store!(CallLists);
    store!(Clear);
    store!(ClearAccum);
    store!(ClearColor);
    store!(ClearDepth);
    store!(ClearIndex);
    store!(ClearStencil);
    store!(ClipPlane);
    store!(Color3b);
    store!(Color3bv);
    store!(Color3d);
    store!(Color3dv);
    store!(Color3f);
    store!(Color3fv);
    store!(Color3i);
    store!(Color3iv);
    store!(Color3s);
    store!(Color3sv);
    store!(Color3ub);
    store!(Color3ubv);
    store!(Color3ui);
    store!(Color3uiv);
    store!(Color3us);
    store!(Color3usv);
    store!(Color4b);
    store!(Color4bv);
    store!(Color4d);
    store!(Color4dv);
    store!(Color4f);
    store!(Color4fv);
    store!(Color4i);
    store!(Color4iv);
    store!(Color4s);
    store!(Color4sv);
    store!(Color4ub);
    store!(Color4ubv);
    store!(Color4ui);
    store!(Color4uiv);
    store!(Color4us);
    store!(Color4usv);
    store!(ColorMask);
    store!(ColorMaterial);
    store!(ColorPointer);
    store!(CopyPixels);
    store!(CopyTexImage1D);
    store!(CopyTexImage2D);
    store!(CopyTexSubImage1D);
    store!(CopyTexSubImage2D);
    store!(CreateMemoryObjectsEXT);
    store!(CullFace);
    store!(DeleteLists);
    store!(DeleteMemoryObjectsEXT);
    store!(DeleteTextures);
    store!(DepthFunc);
    store!(DepthMask);
    store!(DepthRange);
    store!(Disable);
    store!(DisableClientState);
    store!(DrawArrays);
    store!(DrawBuffer);
    store!(DrawElements);
    store!(DrawPixels);
    store!(EdgeFlag);
    store!(EdgeFlagPointer);
    store!(EdgeFlagv);
    store!(Enable);
    store!(EnableClientState);
    store!(End);
    store!(EndList);
    store!(EvalCoord1d);
    store!(EvalCoord1dv);
    store!(EvalCoord1f);
    store!(EvalCoord1fv);
    store!(EvalCoord2d);
    store!(EvalCoord2dv);
    store!(EvalCoord2f);
    store!(EvalCoord2fv);
    store!(EvalMesh1);
    store!(EvalMesh2);
    store!(EvalPoint1);
    store!(EvalPoint2);
    store!(FeedbackBuffer);
    store!(Finish);
    store!(Flush);
    store!(Fogf);
    store!(Fogfv);
    store!(Fogi);
    store!(Fogiv);
    store!(FrontFace);
    store!(Frustum);
    store!(GenLists);
    store!(GenTextures);
    store!(GetBooleanv);
    store!(GetClipPlane);
    store!(GetDoublev);
    store!(GetError);
    store!(GetFloatv);
    store!(GetIntegerv);
    store!(GetLightfv);
    store!(GetLightiv);
    store!(GetMapdv);
    store!(GetMapfv);
    store!(GetMapiv);
    store!(GetMaterialfv);
    store!(GetMaterialiv);
    store!(GetMemoryObjectParameterivEXT);
    store!(GetPixelMapfv);
    store!(GetPixelMapuiv);
    store!(GetPixelMapusv);
    store!(GetPointerv);
    store!(GetPolygonStipple);
    store!(GetString);
    store!(GetTexEnvfv);
    store!(GetTexEnviv);
    store!(GetTexGendv);
    store!(GetTexGenfv);
    store!(GetTexGeniv);
    store!(GetTexImage);
    store!(GetTexLevelParameterfv);
    store!(GetTexLevelParameteriv);
    store!(GetTexParameterfv);
    store!(GetTexParameteriv);
    store!(GetUnsignedBytei_vEXT);
    store!(GetUnsignedBytevEXT);
    store!(Hint);
    store!(ImportMemoryWin32HandleEXT);
    store!(ImportMemoryWin32NameEXT);
    store!(IndexMask);
    store!(IndexPointer);
    store!(Indexd);
    store!(Indexdv);
    store!(Indexf);
    store!(Indexfv);
    store!(Indexi);
    store!(Indexiv);
    store!(Indexs);
    store!(Indexsv);
    store!(Indexub);
    store!(Indexubv);
    store!(InitNames);
    store!(InterleavedArrays);
    store!(IsEnabled);
    store!(IsList);
    store!(IsMemoryObjectEXT);
    store!(IsTexture);
    store!(LightModelf);
    store!(LightModelfv);
    store!(LightModeli);
    store!(LightModeliv);
    store!(Lightf);
    store!(Lightfv);
    store!(Lighti);
    store!(Lightiv);
    store!(LineStipple);
    store!(LineWidth);
    store!(ListBase);
    store!(LoadIdentity);
    store!(LoadMatrixd);
    store!(LoadMatrixf);
    store!(LoadName);
    store!(LogicOp);
    store!(Map1d);
    store!(Map1f);
    store!(Map2d);
    store!(Map2f);
    store!(MapGrid1d);
    store!(MapGrid1f);
    store!(MapGrid2d);
    store!(MapGrid2f);
    store!(Materialf);
    store!(Materialfv);
    store!(Materiali);
    store!(Materialiv);
    store!(MatrixMode);
    store!(MemoryObjectParameterivEXT);
    store!(MultMatrixd);
    store!(MultMatrixf);
    store!(NamedBufferStorageMemEXT);
    store!(NewList);
    store!(Normal3b);
    store!(Normal3bv);
    store!(Normal3d);
    store!(Normal3dv);
    store!(Normal3f);
    store!(Normal3fv);
    store!(Normal3i);
    store!(Normal3iv);
    store!(Normal3s);
    store!(Normal3sv);
    store!(NormalPointer);
    store!(Ortho);
    store!(PassThrough);
    store!(PixelMapfv);
    store!(PixelMapuiv);
    store!(PixelMapusv);
    store!(PixelStoref);
    store!(PixelStorei);
    store!(PixelTransferf);
    store!(PixelTransferi);
    store!(PixelZoom);
    store!(PointSize);
    store!(PolygonMode);
    store!(PolygonOffset);
    store!(PolygonStipple);
    store!(PopAttrib);
    store!(PopClientAttrib);
    store!(PopMatrix);
    store!(PopName);
    store!(PrioritizeTextures);
    store!(PushAttrib);
    store!(PushClientAttrib);
    store!(PushMatrix);
    store!(PushName);
    store!(RasterPos2d);
    store!(RasterPos2dv);
    store!(RasterPos2f);
    store!(RasterPos2fv);
    store!(RasterPos2i);
    store!(RasterPos2iv);
    store!(RasterPos2s);
    store!(RasterPos2sv);
    store!(RasterPos3d);
    store!(RasterPos3dv);
    store!(RasterPos3f);
    store!(RasterPos3fv);
    store!(RasterPos3i);
    store!(RasterPos3iv);
    store!(RasterPos3s);
    store!(RasterPos3sv);
    store!(RasterPos4d);
    store!(RasterPos4dv);
    store!(RasterPos4f);
    store!(RasterPos4fv);
    store!(RasterPos4i);
    store!(RasterPos4iv);
    store!(RasterPos4s);
    store!(RasterPos4sv);
    store!(ReadBuffer);
    store!(ReadPixels);
    store!(Rectd);
    store!(Rectdv);
    store!(Rectf);
    store!(Rectfv);
    store!(Recti);
    store!(Rectiv);
    store!(Rects);
    store!(Rectsv);
    store!(RenderMode);
    store!(Rotated);
    store!(Rotatef);
    store!(Scaled);
    store!(Scalef);
    store!(Scissor);
    store!(SelectBuffer);
    store!(ShadeModel);
    store!(StencilFunc);
    store!(StencilMask);
    store!(StencilOp);
    store!(TexCoord1d);
    store!(TexCoord1dv);
    store!(TexCoord1f);
    store!(TexCoord1fv);
    store!(TexCoord1i);
    store!(TexCoord1iv);
    store!(TexCoord1s);
    store!(TexCoord1sv);
    store!(TexCoord2d);
    store!(TexCoord2dv);
    store!(TexCoord2f);
    store!(TexCoord2fv);
    store!(TexCoord2i);
    store!(TexCoord2iv);
    store!(TexCoord2s);
    store!(TexCoord2sv);
    store!(TexCoord3d);
    store!(TexCoord3dv);
    store!(TexCoord3f);
    store!(TexCoord3fv);
    store!(TexCoord3i);
    store!(TexCoord3iv);
    store!(TexCoord3s);
    store!(TexCoord3sv);
    store!(TexCoord4d);
    store!(TexCoord4dv);
    store!(TexCoord4f);
    store!(TexCoord4fv);
    store!(TexCoord4i);
    store!(TexCoord4iv);
    store!(TexCoord4s);
    store!(TexCoord4sv);
    store!(TexCoordPointer);
    store!(TexEnvf);
    store!(TexEnvfv);
    store!(TexEnvi);
    store!(TexEnviv);
    store!(TexGend);
    store!(TexGendv);
    store!(TexGenf);
    store!(TexGenfv);
    store!(TexGeni);
    store!(TexGeniv);
    store!(TexImage1D);
    store!(TexImage2D);
    store!(TexParameterf);
    store!(TexParameterfv);
    store!(TexParameteri);
    store!(TexParameteriv);
    store!(TexStorageMem1DEXT);
    store!(TexStorageMem2DEXT);
    store!(TexStorageMem2DMultisampleEXT);
    store!(TexStorageMem3DEXT);
    store!(TexStorageMem3DMultisampleEXT);
    store!(TexSubImage1D);
    store!(TexSubImage2D);
    store!(TextureStorageMem1DEXT);
    store!(TextureStorageMem2DEXT);
    store!(TextureStorageMem2DMultisampleEXT);
    store!(TextureStorageMem3DEXT);
    store!(TextureStorageMem3DMultisampleEXT);
    store!(Translated);
    store!(Translatef);
    store!(Vertex2d);
    store!(Vertex2dv);
    store!(Vertex2f);
    store!(Vertex2fv);
    store!(Vertex2i);
    store!(Vertex2iv);
    store!(Vertex2s);
    store!(Vertex2sv);
    store!(Vertex3d);
    store!(Vertex3dv);
    store!(Vertex3f);
    store!(Vertex3fv);
    store!(Vertex3i);
    store!(Vertex3iv);
    store!(Vertex3s);
    store!(Vertex3sv);
    store!(Vertex4d);
    store!(Vertex4dv);
    store!(Vertex4f);
    store!(Vertex4fv);
    store!(Vertex4i);
    store!(Vertex4iv);
    store!(Vertex4s);
    store!(Vertex4sv);
    store!(VertexPointer);
    store!(Viewport);
}

pub fn load<F>(mut loadfn: F)
where
    F: FnMut(&'static str) -> *const c_void,
{
    storage::Accum.set_ptr(loadfn("glAccum"));
    storage::AlphaFunc.set_ptr(loadfn("glAlphaFunc"));
    storage::AreTexturesResident.set_ptr(loadfn("glAreTexturesResident"));
    storage::ArrayElement.set_ptr(loadfn("glArrayElement"));
    storage::Begin.set_ptr(loadfn("glBegin"));
    storage::BindTexture.set_ptr(loadfn("glBindTexture"));
    storage::Bitmap.set_ptr(loadfn("glBitmap"));
    storage::BlendFunc.set_ptr(loadfn("glBlendFunc"));
    storage::BufferStorageMemEXT.set_ptr(loadfn("glBufferStorageMemEXT"));
    storage::CallList.set_ptr(loadfn("glCallList"));
    storage::CallLists.set_ptr(loadfn("glCallLists"));
    storage::Clear.set_ptr(loadfn("glClear"));
    storage::ClearAccum.set_ptr(loadfn("glClearAccum"));
    storage::ClearColor.set_ptr(loadfn("glClearColor"));
    storage::ClearDepth.set_ptr(loadfn("glClearDepth"));
    storage::ClearIndex.set_ptr(loadfn("glClearIndex"));
    storage::ClearStencil.set_ptr(loadfn("glClearStencil"));
    storage::ClipPlane.set_ptr(loadfn("glClipPlane"));
    storage::Color3b.set_ptr(loadfn("glColor3b"));
    storage::Color3bv.set_ptr(loadfn("glColor3bv"));
    storage::Color3d.set_ptr(loadfn("glColor3d"));
    storage::Color3dv.set_ptr(loadfn("glColor3dv"));
    storage::Color3f.set_ptr(loadfn("glColor3f"));
    storage::Color3fv.set_ptr(loadfn("glColor3fv"));
    storage::Color3i.set_ptr(loadfn("glColor3i"));
    storage::Color3iv.set_ptr(loadfn("glColor3iv"));
    storage::Color3s.set_ptr(loadfn("glColor3s"));
    storage::Color3sv.set_ptr(loadfn("glColor3sv"));
    storage::Color3ub.set_ptr(loadfn("glColor3ub"));
    storage::Color3ubv.set_ptr(loadfn("glColor3ubv"));
    storage::Color3ui.set_ptr(loadfn("glColor3ui"));
    storage::Color3uiv.set_ptr(loadfn("glColor3uiv"));
    storage::Color3us.set_ptr(loadfn("glColor3us"));
    storage::Color3usv.set_ptr(loadfn("glColor3usv"));
    storage::Color4b.set_ptr(loadfn("glColor4b"));
    storage::Color4bv.set_ptr(loadfn("glColor4bv"));
    storage::Color4d.set_ptr(loadfn("glColor4d"));
    storage::Color4dv.set_ptr(loadfn("glColor4dv"));
    storage::Color4f.set_ptr(loadfn("glColor4f"));
    storage::Color4fv.set_ptr(loadfn("glColor4fv"));
    storage::Color4i.set_ptr(loadfn("glColor4i"));
    storage::Color4iv.set_ptr(loadfn("glColor4iv"));
    storage::Color4s.set_ptr(loadfn("glColor4s"));
    storage::Color4sv.set_ptr(loadfn("glColor4sv"));
    storage::Color4ub.set_ptr(loadfn("glColor4ub"));
    storage::Color4ubv.set_ptr(loadfn("glColor4ubv"));
    storage::Color4ui.set_ptr(loadfn("glColor4ui"));
    storage::Color4uiv.set_ptr(loadfn("glColor4uiv"));
    storage::Color4us.set_ptr(loadfn("glColor4us"));
    storage::Color4usv.set_ptr(loadfn("glColor4usv"));
    storage::ColorMask.set_ptr(loadfn("glColorMask"));
    storage::ColorMaterial.set_ptr(loadfn("glColorMaterial"));
    storage::ColorPointer.set_ptr(loadfn("glColorPointer"));
    storage::CopyPixels.set_ptr(loadfn("glCopyPixels"));
    storage::CopyTexImage1D.set_ptr(loadfn("glCopyTexImage1D"));
    storage::CopyTexImage2D.set_ptr(loadfn("glCopyTexImage2D"));
    storage::CopyTexSubImage1D.set_ptr(loadfn("glCopyTexSubImage1D"));
    storage::CopyTexSubImage2D.set_ptr(loadfn("glCopyTexSubImage2D"));
    storage::CreateMemoryObjectsEXT.set_ptr(loadfn("glCreateMemoryObjectsEXT"));
    storage::CullFace.set_ptr(loadfn("glCullFace"));
    storage::DeleteLists.set_ptr(loadfn("glDeleteLists"));
    storage::DeleteMemoryObjectsEXT.set_ptr(loadfn("glDeleteMemoryObjectsEXT"));
    storage::DeleteTextures.set_ptr(loadfn("glDeleteTextures"));
    storage::DepthFunc.set_ptr(loadfn("glDepthFunc"));
    storage::DepthMask.set_ptr(loadfn("glDepthMask"));
    storage::DepthRange.set_ptr(loadfn("glDepthRange"));
    storage::Disable.set_ptr(loadfn("glDisable"));
    storage::DisableClientState.set_ptr(loadfn("glDisableClientState"));
    storage::DrawArrays.set_ptr(loadfn("glDrawArrays"));
    storage::DrawBuffer.set_ptr(loadfn("glDrawBuffer"));
    storage::DrawElements.set_ptr(loadfn("glDrawElements"));
    storage::DrawPixels.set_ptr(loadfn("glDrawPixels"));
    storage::EdgeFlag.set_ptr(loadfn("glEdgeFlag"));
    storage::EdgeFlagPointer.set_ptr(loadfn("glEdgeFlagPointer"));
    storage::EdgeFlagv.set_ptr(loadfn("glEdgeFlagv"));
    storage::Enable.set_ptr(loadfn("glEnable"));
    storage::EnableClientState.set_ptr(loadfn("glEnableClientState"));
    storage::End.set_ptr(loadfn("glEnd"));
    storage::EndList.set_ptr(loadfn("glEndList"));
    storage::EvalCoord1d.set_ptr(loadfn("glEvalCoord1d"));
    storage::EvalCoord1dv.set_ptr(loadfn("glEvalCoord1dv"));
    storage::EvalCoord1f.set_ptr(loadfn("glEvalCoord1f"));
    storage::EvalCoord1fv.set_ptr(loadfn("glEvalCoord1fv"));
    storage::EvalCoord2d.set_ptr(loadfn("glEvalCoord2d"));
    storage::EvalCoord2dv.set_ptr(loadfn("glEvalCoord2dv"));
    storage::EvalCoord2f.set_ptr(loadfn("glEvalCoord2f"));
    storage::EvalCoord2fv.set_ptr(loadfn("glEvalCoord2fv"));
    storage::EvalMesh1.set_ptr(loadfn("glEvalMesh1"));
    storage::EvalMesh2.set_ptr(loadfn("glEvalMesh2"));
    storage::EvalPoint1.set_ptr(loadfn("glEvalPoint1"));
    storage::EvalPoint2.set_ptr(loadfn("glEvalPoint2"));
    storage::FeedbackBuffer.set_ptr(loadfn("glFeedbackBuffer"));
    storage::Finish.set_ptr(loadfn("glFinish"));
    storage::Flush.set_ptr(loadfn("glFlush"));
    storage::Fogf.set_ptr(loadfn("glFogf"));
    storage::Fogfv.set_ptr(loadfn("glFogfv"));
    storage::Fogi.set_ptr(loadfn("glFogi"));
    storage::Fogiv.set_ptr(loadfn("glFogiv"));
    storage::FrontFace.set_ptr(loadfn("glFrontFace"));
    storage::Frustum.set_ptr(loadfn("glFrustum"));
    storage::GenLists.set_ptr(loadfn("glGenLists"));
    storage::GenTextures.set_ptr(loadfn("glGenTextures"));
    storage::GetBooleanv.set_ptr(loadfn("glGetBooleanv"));
    storage::GetClipPlane.set_ptr(loadfn("glGetClipPlane"));
    storage::GetDoublev.set_ptr(loadfn("glGetDoublev"));
    storage::GetError.set_ptr(loadfn("glGetError"));
    storage::GetFloatv.set_ptr(loadfn("glGetFloatv"));
    storage::GetIntegerv.set_ptr(loadfn("glGetIntegerv"));
    storage::GetLightfv.set_ptr(loadfn("glGetLightfv"));
    storage::GetLightiv.set_ptr(loadfn("glGetLightiv"));
    storage::GetMapdv.set_ptr(loadfn("glGetMapdv"));
    storage::GetMapfv.set_ptr(loadfn("glGetMapfv"));
    storage::GetMapiv.set_ptr(loadfn("glGetMapiv"));
    storage::GetMaterialfv.set_ptr(loadfn("glGetMaterialfv"));
    storage::GetMaterialiv.set_ptr(loadfn("glGetMaterialiv"));
    storage::GetMemoryObjectParameterivEXT.set_ptr(loadfn("glGetMemoryObjectParameterivEXT"));
    storage::GetPixelMapfv.set_ptr(loadfn("glGetPixelMapfv"));
    storage::GetPixelMapuiv.set_ptr(loadfn("glGetPixelMapuiv"));
    storage::GetPixelMapusv.set_ptr(loadfn("glGetPixelMapusv"));
    storage::GetPointerv.set_ptr(loadfn("glGetPointerv"));
    storage::GetPolygonStipple.set_ptr(loadfn("glGetPolygonStipple"));
    storage::GetString.set_ptr(loadfn("glGetString"));
    storage::GetTexEnvfv.set_ptr(loadfn("glGetTexEnvfv"));
    storage::GetTexEnviv.set_ptr(loadfn("glGetTexEnviv"));
    storage::GetTexGendv.set_ptr(loadfn("glGetTexGendv"));
    storage::GetTexGenfv.set_ptr(loadfn("glGetTexGenfv"));
    storage::GetTexGeniv.set_ptr(loadfn("glGetTexGeniv"));
    storage::GetTexImage.set_ptr(loadfn("glGetTexImage"));
    storage::GetTexLevelParameterfv.set_ptr(loadfn("glGetTexLevelParameterfv"));
    storage::GetTexLevelParameteriv.set_ptr(loadfn("glGetTexLevelParameteriv"));
    storage::GetTexParameterfv.set_ptr(loadfn("glGetTexParameterfv"));
    storage::GetTexParameteriv.set_ptr(loadfn("glGetTexParameteriv"));
    storage::GetUnsignedBytei_vEXT.set_ptr(loadfn("glGetUnsignedBytei_vEXT"));
    storage::GetUnsignedBytevEXT.set_ptr(loadfn("glGetUnsignedBytevEXT"));
    storage::Hint.set_ptr(loadfn("glHint"));
    storage::ImportMemoryWin32HandleEXT.set_ptr(loadfn("glImportMemoryWin32HandleEXT"));
    storage::ImportMemoryWin32NameEXT.set_ptr(loadfn("glImportMemoryWin32NameEXT"));
    storage::IndexMask.set_ptr(loadfn("glIndexMask"));
    storage::IndexPointer.set_ptr(loadfn("glIndexPointer"));
    storage::Indexd.set_ptr(loadfn("glIndexd"));
    storage::Indexdv.set_ptr(loadfn("glIndexdv"));
    storage::Indexf.set_ptr(loadfn("glIndexf"));
    storage::Indexfv.set_ptr(loadfn("glIndexfv"));
    storage::Indexi.set_ptr(loadfn("glIndexi"));
    storage::Indexiv.set_ptr(loadfn("glIndexiv"));
    storage::Indexs.set_ptr(loadfn("glIndexs"));
    storage::Indexsv.set_ptr(loadfn("glIndexsv"));
    storage::Indexub.set_ptr(loadfn("glIndexub"));
    storage::Indexubv.set_ptr(loadfn("glIndexubv"));
    storage::InitNames.set_ptr(loadfn("glInitNames"));
    storage::InterleavedArrays.set_ptr(loadfn("glInterleavedArrays"));
    storage::IsEnabled.set_ptr(loadfn("glIsEnabled"));
    storage::IsList.set_ptr(loadfn("glIsList"));
    storage::IsMemoryObjectEXT.set_ptr(loadfn("glIsMemoryObjectEXT"));
    storage::IsTexture.set_ptr(loadfn("glIsTexture"));
    storage::LightModelf.set_ptr(loadfn("glLightModelf"));
    storage::LightModelfv.set_ptr(loadfn("glLightModelfv"));
    storage::LightModeli.set_ptr(loadfn("glLightModeli"));
    storage::LightModeliv.set_ptr(loadfn("glLightModeliv"));
    storage::Lightf.set_ptr(loadfn("glLightf"));
    storage::Lightfv.set_ptr(loadfn("glLightfv"));
    storage::Lighti.set_ptr(loadfn("glLighti"));
    storage::Lightiv.set_ptr(loadfn("glLightiv"));
    storage::LineStipple.set_ptr(loadfn("glLineStipple"));
    storage::LineWidth.set_ptr(loadfn("glLineWidth"));
    storage::ListBase.set_ptr(loadfn("glListBase"));
    storage::LoadIdentity.set_ptr(loadfn("glLoadIdentity"));
    storage::LoadMatrixd.set_ptr(loadfn("glLoadMatrixd"));
    storage::LoadMatrixf.set_ptr(loadfn("glLoadMatrixf"));
    storage::LoadName.set_ptr(loadfn("glLoadName"));
    storage::LogicOp.set_ptr(loadfn("glLogicOp"));
    storage::Map1d.set_ptr(loadfn("glMap1d"));
    storage::Map1f.set_ptr(loadfn("glMap1f"));
    storage::Map2d.set_ptr(loadfn("glMap2d"));
    storage::Map2f.set_ptr(loadfn("glMap2f"));
    storage::MapGrid1d.set_ptr(loadfn("glMapGrid1d"));
    storage::MapGrid1f.set_ptr(loadfn("glMapGrid1f"));
    storage::MapGrid2d.set_ptr(loadfn("glMapGrid2d"));
    storage::MapGrid2f.set_ptr(loadfn("glMapGrid2f"));
    storage::Materialf.set_ptr(loadfn("glMaterialf"));
    storage::Materialfv.set_ptr(loadfn("glMaterialfv"));
    storage::Materiali.set_ptr(loadfn("glMateriali"));
    storage::Materialiv.set_ptr(loadfn("glMaterialiv"));
    storage::MatrixMode.set_ptr(loadfn("glMatrixMode"));
    storage::MemoryObjectParameterivEXT.set_ptr(loadfn("glMemoryObjectParameterivEXT"));
    storage::MultMatrixd.set_ptr(loadfn("glMultMatrixd"));
    storage::MultMatrixf.set_ptr(loadfn("glMultMatrixf"));
    storage::NamedBufferStorageMemEXT.set_ptr(loadfn("glNamedBufferStorageMemEXT"));
    storage::NewList.set_ptr(loadfn("glNewList"));
    storage::Normal3b.set_ptr(loadfn("glNormal3b"));
    storage::Normal3bv.set_ptr(loadfn("glNormal3bv"));
    storage::Normal3d.set_ptr(loadfn("glNormal3d"));
    storage::Normal3dv.set_ptr(loadfn("glNormal3dv"));
    storage::Normal3f.set_ptr(loadfn("glNormal3f"));
    storage::Normal3fv.set_ptr(loadfn("glNormal3fv"));
    storage::Normal3i.set_ptr(loadfn("glNormal3i"));
    storage::Normal3iv.set_ptr(loadfn("glNormal3iv"));
    storage::Normal3s.set_ptr(loadfn("glNormal3s"));
    storage::Normal3sv.set_ptr(loadfn("glNormal3sv"));
    storage::NormalPointer.set_ptr(loadfn("glNormalPointer"));
    storage::Ortho.set_ptr(loadfn("glOrtho"));
    storage::PassThrough.set_ptr(loadfn("glPassThrough"));
    storage::PixelMapfv.set_ptr(loadfn("glPixelMapfv"));
    storage::PixelMapuiv.set_ptr(loadfn("glPixelMapuiv"));
    storage::PixelMapusv.set_ptr(loadfn("glPixelMapusv"));
    storage::PixelStoref.set_ptr(loadfn("glPixelStoref"));
    storage::PixelStorei.set_ptr(loadfn("glPixelStorei"));
    storage::PixelTransferf.set_ptr(loadfn("glPixelTransferf"));
    storage::PixelTransferi.set_ptr(loadfn("glPixelTransferi"));
    storage::PixelZoom.set_ptr(loadfn("glPixelZoom"));
    storage::PointSize.set_ptr(loadfn("glPointSize"));
    storage::PolygonMode.set_ptr(loadfn("glPolygonMode"));
    storage::PolygonOffset.set_ptr(loadfn("glPolygonOffset"));
    storage::PolygonStipple.set_ptr(loadfn("glPolygonStipple"));
    storage::PopAttrib.set_ptr(loadfn("glPopAttrib"));
    storage::PopClientAttrib.set_ptr(loadfn("glPopClientAttrib"));
    storage::PopMatrix.set_ptr(loadfn("glPopMatrix"));
    storage::PopName.set_ptr(loadfn("glPopName"));
    storage::PrioritizeTextures.set_ptr(loadfn("glPrioritizeTextures"));
    storage::PushAttrib.set_ptr(loadfn("glPushAttrib"));
    storage::PushClientAttrib.set_ptr(loadfn("glPushClientAttrib"));
    storage::PushMatrix.set_ptr(loadfn("glPushMatrix"));
    storage::PushName.set_ptr(loadfn("glPushName"));
    storage::RasterPos2d.set_ptr(loadfn("glRasterPos2d"));
    storage::RasterPos2dv.set_ptr(loadfn("glRasterPos2dv"));
    storage::RasterPos2f.set_ptr(loadfn("glRasterPos2f"));
    storage::RasterPos2fv.set_ptr(loadfn("glRasterPos2fv"));
    storage::RasterPos2i.set_ptr(loadfn("glRasterPos2i"));
    storage::RasterPos2iv.set_ptr(loadfn("glRasterPos2iv"));
    storage::RasterPos2s.set_ptr(loadfn("glRasterPos2s"));
    storage::RasterPos2sv.set_ptr(loadfn("glRasterPos2sv"));
    storage::RasterPos3d.set_ptr(loadfn("glRasterPos3d"));
    storage::RasterPos3dv.set_ptr(loadfn("glRasterPos3dv"));
    storage::RasterPos3f.set_ptr(loadfn("glRasterPos3f"));
    storage::RasterPos3fv.set_ptr(loadfn("glRasterPos3fv"));
    storage::RasterPos3i.set_ptr(loadfn("glRasterPos3i"));
    storage::RasterPos3iv.set_ptr(loadfn("glRasterPos3iv"));
    storage::RasterPos3s.set_ptr(loadfn("glRasterPos3s"));
    storage::RasterPos3sv.set_ptr(loadfn("glRasterPos3sv"));
    storage::RasterPos4d.set_ptr(loadfn("glRasterPos4d"));
    storage::RasterPos4dv.set_ptr(loadfn("glRasterPos4dv"));
    storage::RasterPos4f.set_ptr(loadfn("glRasterPos4f"));
    storage::RasterPos4fv.set_ptr(loadfn("glRasterPos4fv"));
    storage::RasterPos4i.set_ptr(loadfn("glRasterPos4i"));
    storage::RasterPos4iv.set_ptr(loadfn("glRasterPos4iv"));
    storage::RasterPos4s.set_ptr(loadfn("glRasterPos4s"));
    storage::RasterPos4sv.set_ptr(loadfn("glRasterPos4sv"));
    storage::ReadBuffer.set_ptr(loadfn("glReadBuffer"));
    storage::ReadPixels.set_ptr(loadfn("glReadPixels"));
    storage::Rectd.set_ptr(loadfn("glRectd"));
    storage::Rectdv.set_ptr(loadfn("glRectdv"));
    storage::Rectf.set_ptr(loadfn("glRectf"));
    storage::Rectfv.set_ptr(loadfn("glRectfv"));
    storage::Recti.set_ptr(loadfn("glRecti"));
    storage::Rectiv.set_ptr(loadfn("glRectiv"));
    storage::Rects.set_ptr(loadfn("glRects"));
    storage::Rectsv.set_ptr(loadfn("glRectsv"));
    storage::RenderMode.set_ptr(loadfn("glRenderMode"));
    storage::Rotated.set_ptr(loadfn("glRotated"));
    storage::Rotatef.set_ptr(loadfn("glRotatef"));
    storage::Scaled.set_ptr(loadfn("glScaled"));
    storage::Scalef.set_ptr(loadfn("glScalef"));
    storage::Scissor.set_ptr(loadfn("glScissor"));
    storage::SelectBuffer.set_ptr(loadfn("glSelectBuffer"));
    storage::ShadeModel.set_ptr(loadfn("glShadeModel"));
    storage::StencilFunc.set_ptr(loadfn("glStencilFunc"));
    storage::StencilMask.set_ptr(loadfn("glStencilMask"));
    storage::StencilOp.set_ptr(loadfn("glStencilOp"));
    storage::TexCoord1d.set_ptr(loadfn("glTexCoord1d"));
    storage::TexCoord1dv.set_ptr(loadfn("glTexCoord1dv"));
    storage::TexCoord1f.set_ptr(loadfn("glTexCoord1f"));
    storage::TexCoord1fv.set_ptr(loadfn("glTexCoord1fv"));
    storage::TexCoord1i.set_ptr(loadfn("glTexCoord1i"));
    storage::TexCoord1iv.set_ptr(loadfn("glTexCoord1iv"));
    storage::TexCoord1s.set_ptr(loadfn("glTexCoord1s"));
    storage::TexCoord1sv.set_ptr(loadfn("glTexCoord1sv"));
    storage::TexCoord2d.set_ptr(loadfn("glTexCoord2d"));
    storage::TexCoord2dv.set_ptr(loadfn("glTexCoord2dv"));
    storage::TexCoord2f.set_ptr(loadfn("glTexCoord2f"));
    storage::TexCoord2fv.set_ptr(loadfn("glTexCoord2fv"));
    storage::TexCoord2i.set_ptr(loadfn("glTexCoord2i"));
    storage::TexCoord2iv.set_ptr(loadfn("glTexCoord2iv"));
    storage::TexCoord2s.set_ptr(loadfn("glTexCoord2s"));
    storage::TexCoord2sv.set_ptr(loadfn("glTexCoord2sv"));
    storage::TexCoord3d.set_ptr(loadfn("glTexCoord3d"));
    storage::TexCoord3dv.set_ptr(loadfn("glTexCoord3dv"));
    storage::TexCoord3f.set_ptr(loadfn("glTexCoord3f"));
    storage::TexCoord3fv.set_ptr(loadfn("glTexCoord3fv"));
    storage::TexCoord3i.set_ptr(loadfn("glTexCoord3i"));
    storage::TexCoord3iv.set_ptr(loadfn("glTexCoord3iv"));
    storage::TexCoord3s.set_ptr(loadfn("glTexCoord3s"));
    storage::TexCoord3sv.set_ptr(loadfn("glTexCoord3sv"));
    storage::TexCoord4d.set_ptr(loadfn("glTexCoord4d"));
    storage::TexCoord4dv.set_ptr(loadfn("glTexCoord4dv"));
    storage::TexCoord4f.set_ptr(loadfn("glTexCoord4f"));
    storage::TexCoord4fv.set_ptr(loadfn("glTexCoord4fv"));
    storage::TexCoord4i.set_ptr(loadfn("glTexCoord4i"));
    storage::TexCoord4iv.set_ptr(loadfn("glTexCoord4iv"));
    storage::TexCoord4s.set_ptr(loadfn("glTexCoord4s"));
    storage::TexCoord4sv.set_ptr(loadfn("glTexCoord4sv"));
    storage::TexCoordPointer.set_ptr(loadfn("glTexCoordPointer"));
    storage::TexEnvf.set_ptr(loadfn("glTexEnvf"));
    storage::TexEnvfv.set_ptr(loadfn("glTexEnvfv"));
    storage::TexEnvi.set_ptr(loadfn("glTexEnvi"));
    storage::TexEnviv.set_ptr(loadfn("glTexEnviv"));
    storage::TexGend.set_ptr(loadfn("glTexGend"));
    storage::TexGendv.set_ptr(loadfn("glTexGendv"));
    storage::TexGenf.set_ptr(loadfn("glTexGenf"));
    storage::TexGenfv.set_ptr(loadfn("glTexGenfv"));
    storage::TexGeni.set_ptr(loadfn("glTexGeni"));
    storage::TexGeniv.set_ptr(loadfn("glTexGeniv"));
    storage::TexImage1D.set_ptr(loadfn("glTexImage1D"));
    storage::TexImage2D.set_ptr(loadfn("glTexImage2D"));
    storage::TexParameterf.set_ptr(loadfn("glTexParameterf"));
    storage::TexParameterfv.set_ptr(loadfn("glTexParameterfv"));
    storage::TexParameteri.set_ptr(loadfn("glTexParameteri"));
    storage::TexParameteriv.set_ptr(loadfn("glTexParameteriv"));
    storage::TexStorageMem1DEXT.set_ptr(loadfn("glTexStorageMem1DEXT"));
    storage::TexStorageMem2DEXT.set_ptr(loadfn("glTexStorageMem2DEXT"));
    storage::TexStorageMem2DMultisampleEXT.set_ptr(loadfn("glTexStorageMem2DMultisampleEXT"));
    storage::TexStorageMem3DEXT.set_ptr(loadfn("glTexStorageMem3DEXT"));
    storage::TexStorageMem3DMultisampleEXT.set_ptr(loadfn("glTexStorageMem3DMultisampleEXT"));
    storage::TexSubImage1D.set_ptr(loadfn("glTexSubImage1D"));
    storage::TexSubImage2D.set_ptr(loadfn("glTexSubImage2D"));
    storage::TextureStorageMem1DEXT.set_ptr(loadfn("glTextureStorageMem1DEXT"));
    storage::TextureStorageMem2DEXT.set_ptr(loadfn("glTextureStorageMem2DEXT"));
    storage::TextureStorageMem2DMultisampleEXT
        .set_ptr(loadfn("glTextureStorageMem2DMultisampleEXT"));
    storage::TextureStorageMem3DEXT.set_ptr(loadfn("glTextureStorageMem3DEXT"));
    storage::TextureStorageMem3DMultisampleEXT
        .set_ptr(loadfn("glTextureStorageMem3DMultisampleEXT"));
    storage::Translated.set_ptr(loadfn("glTranslated"));
    storage::Translatef.set_ptr(loadfn("glTranslatef"));
    storage::Vertex2d.set_ptr(loadfn("glVertex2d"));
    storage::Vertex2dv.set_ptr(loadfn("glVertex2dv"));
    storage::Vertex2f.set_ptr(loadfn("glVertex2f"));
    storage::Vertex2fv.set_ptr(loadfn("glVertex2fv"));
    storage::Vertex2i.set_ptr(loadfn("glVertex2i"));
    storage::Vertex2iv.set_ptr(loadfn("glVertex2iv"));
    storage::Vertex2s.set_ptr(loadfn("glVertex2s"));
    storage::Vertex2sv.set_ptr(loadfn("glVertex2sv"));
    storage::Vertex3d.set_ptr(loadfn("glVertex3d"));
    storage::Vertex3dv.set_ptr(loadfn("glVertex3dv"));
    storage::Vertex3f.set_ptr(loadfn("glVertex3f"));
    storage::Vertex3fv.set_ptr(loadfn("glVertex3fv"));
    storage::Vertex3i.set_ptr(loadfn("glVertex3i"));
    storage::Vertex3iv.set_ptr(loadfn("glVertex3iv"));
    storage::Vertex3s.set_ptr(loadfn("glVertex3s"));
    storage::Vertex3sv.set_ptr(loadfn("glVertex3sv"));
    storage::Vertex4d.set_ptr(loadfn("glVertex4d"));
    storage::Vertex4dv.set_ptr(loadfn("glVertex4dv"));
    storage::Vertex4f.set_ptr(loadfn("glVertex4f"));
    storage::Vertex4fv.set_ptr(loadfn("glVertex4fv"));
    storage::Vertex4i.set_ptr(loadfn("glVertex4i"));
    storage::Vertex4iv.set_ptr(loadfn("glVertex4iv"));
    storage::Vertex4s.set_ptr(loadfn("glVertex4s"));
    storage::Vertex4sv.set_ptr(loadfn("glVertex4sv"));
    storage::VertexPointer.set_ptr(loadfn("glVertexPointer"));
    storage::Viewport.set_ptr(loadfn("glViewport"));
}
