[package]
name = "screen_recorder"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
windows.workspace = true
# interprocess.workspace = true
# shared_memory.workspace = true
glad-gl.workspace = true
shmem.workspace = true
vulkanalia = { version = "0.28.0", features = ["libloading", "window"] }
retour = { version = "0.3.1" }
shared_defs = { version = "0.1.0", path = "../shared_defs" }
